"""Access to the vendored Salmon Data Package schema bundle.

Mirrors metasalmon's ``R/schema-helpers.R`` for the part this milestone needs:
the canonical contract identifiers written into packages, and the vendored
Frictionless bundle those identifiers describe.

The bundle under ``data/schema`` and ``data/profiles`` is a verbatim copy of
the **``sdp-0.2.0`` git tag** of ``salmon-data-mobilization/smn-data-pkg`` —
not of that repository's ``main``, which is ``sdp-0.3.0``-shaped and no longer
carries ``methods.schema.json``. metasalmon vendors the identical files at its
own ``v0.1.8`` tag (verified byte-for-byte).

Remote schema discovery is deliberately absent here. metasalmon gained a
remote loader with a branch/commit override before this milestone, but the
replay assigns it to the ``0.2.0`` rung together with the per-resource schema
URLs it feeds; building it now would mean building an interim shape only to
rewrite it. Until then the vendored bundle is the only source, which is also
what metasalmon falls back to when the network is unavailable.
"""

from __future__ import annotations

import json
import re
from functools import lru_cache
from pathlib import Path
from typing import List

_DATA_DIR = Path(__file__).resolve().parent / "data"

# These are contract values stamped into packages, not fetch endpoints. They
# name the canonical publication host; metasalmon corrected the same three
# constants from ``dfo-pacific-science`` at v0.1.8.
SDP_PROFILE_URL = (
    "https://salmon-data-mobilization.github.io/smn-data-pkg/"
    "profiles/salmon-data-package/v0.2/profile.json"
)
SDP_PUBLIC_SCHEMA_BASE = (
    "https://salmon-data-mobilization.github.io/smn-data-pkg/"
    "schema/frictionless/metadata"
)
SDP_RULES_URL = (
    "https://salmon-data-mobilization.github.io/smn-data-pkg/schema/sdp.rules.yaml"
)

SDP_METADATA_SCHEMA_PATHS = {
    "dataset": "schema/frictionless/metadata/dataset.schema.json",
    "tables": "schema/frictionless/metadata/tables.schema.json",
    "column_dictionary": "schema/frictionless/metadata/column_dictionary.schema.json",
    "codes": "schema/frictionless/metadata/codes.schema.json",
    "methods": "schema/frictionless/metadata/methods.schema.json",
    "observation_structures": (
        "schema/frictionless/metadata/observation_structures.schema.json"
    ),
    "observation_components": (
        "schema/frictionless/metadata/observation_components.schema.json"
    ),
}

SDP_RULES_PATH = "schema/sdp.rules.yaml"
SDP_PROFILE_PATH = "profiles/salmon-data-package/v0.2/profile.json"

# ``version: sdp-0.2.0`` -- the first top-level scalar in the rules document.
_RULES_VERSION_RE = re.compile(r"^version:[ \t]*(?:\"([^\"]*)\"|'([^']*)'|(\S+))\s*$")


def vendored_path(relative: str) -> Path:
    """Absolute path to one file of the vendored ``sdp-0.2.0`` bundle."""
    return _DATA_DIR / relative


@lru_cache(maxsize=None)
def sdp_profile_version() -> str:
    """The profile version declared by the vendored ``sdp.rules.yaml``.

    metasalmon reads the same key with ``yaml::read_yaml``. Core dependencies
    here are pandas + requests, so rather than pull PyYAML into the core for
    one scalar this reads the single top-level ``version:`` line. The rules
    document is machine-generated by ``smn-data-pkg``'s
    ``scripts/generate_artifacts.py`` and has carried that key as a plain
    top-level scalar in every published version.

    **Retirement condition:** replace the line scan with a full YAML parse the
    day this package needs any *other* field of ``sdp.rules.yaml`` — at that
    point PyYAML is already justified and the narrow reader is a liability. If
    the scan ever fails to find the key it raises rather than guessing, so a
    format change surfaces as an error instead of a silently stale version.
    """
    path = vendored_path(SDP_RULES_PATH)
    with path.open("r", encoding="utf-8") as stream:
        for line in stream:
            match = _RULES_VERSION_RE.match(line.rstrip("\n"))
            if match:
                return next(group for group in match.groups() if group is not None)
    raise ValueError(
        f"Vendored SDP rules bundle {path} declares no top-level 'version:' key."
    )


@lru_cache(maxsize=None)
def _schema_document(table_name: str) -> dict:
    try:
        relative = SDP_METADATA_SCHEMA_PATHS[table_name]
    except KeyError:
        raise KeyError(
            f"Unknown SDP metadata table {table_name!r}; expected one of "
            + ", ".join(sorted(SDP_METADATA_SCHEMA_PATHS))
            + "."
        ) from None
    with vendored_path(relative).open("r", encoding="utf-8") as stream:
        return json.load(stream)


def sdp_schema_field_names(table_name: str) -> List[str]:
    """Field names, in order, from one vendored Frictionless table schema.

    Mirrors ``.ms_sdp_schema_field_names()``. The writers and readers in
    ``sdp_methods`` and ``observation_structures`` declare their own column
    tuples for clarity; a test asserts those tuples equal what this returns,
    which is how a spec/implementation drift becomes a failing test instead of
    a package that writes columns the profile does not define.
    """
    document = _schema_document(table_name)
    return [str(field["name"]) for field in document.get("fields", [])]


def sdp_schema_url(schema_file: str) -> str:
    """The canonical published URL for one Frictionless metadata schema."""
    return f"{SDP_PUBLIC_SCHEMA_BASE}/{schema_file}"


__all__ = [
    "SDP_METADATA_SCHEMA_PATHS",
    "SDP_PROFILE_PATH",
    "SDP_PROFILE_URL",
    "SDP_PUBLIC_SCHEMA_BASE",
    "SDP_RULES_PATH",
    "SDP_RULES_URL",
    "sdp_profile_version",
    "sdp_schema_field_names",
    "sdp_schema_url",
    "vendored_path",
]
