"""
Offline parity tests for KNB/DataONE publication (metasalmon 0.1.7 parity).

Fixtures under ``tests/data/knb/`` were generated by running metasalmon at the
**v0.1.7 tag** (R 4.5.2, zip 3.0.1, datapack 1.4.2, emld 0.5.3 — see
``expected.json["generated_by"]``): two source SDPs, the dry-run manifests,
OAI-ORE resource maps and deterministic SDP ZIP R produced from them, the exact
JSON payload R hashes into ``plan_sha256``, the SystemMetadata documents R
uploads, and a table of pure-helper return values.

**No test touches the network.** Every live-path test injects a fake adapter
through ``set_knb_adapter``, mirroring R's ``metasalmon.knb_adapter`` option;
the dry-run tests install an adapter whose every method raises, which is the
sentinel proving no adapter is constructed on the planning path.

Parity boundaries, and why they are where they are:

* **Byte-exact with R** — the plan fingerprint payload and its SHA-256, the
  recovery manifest JSON, every identifier (resource-map PID, archive PID,
  artifact PIDs), the Solr catalog URL, redaction, and the ORE/SystemMetadata
  documents compared with ``ET.canonicalize``.
* **Contract-level only** — the SDP ZIP (R pins ``zip`` 3.0.1; Python defines
  its own :mod:`zipfile` determinism reference) and the EML document (libxml2
  vs ElementTree). Because those two artifacts' *bytes* differ, so do the
  archive and resource-map object checksums Python computes end to end — which
  is why the exact-parity tests drive the planner from R's own member table
  rather than from a Python-built archive. PARITY.md entries 4, 15, 17.
"""

import json
import os
import shutil
import tempfile
import unittest
import xml.etree.ElementTree as ET

try:
    import pandas as pd
except ImportError:  # pragma: no cover
    pd = None

if pd is None:
    raise unittest.SkipTest("pandas not installed")

import metasalmonpy.knb_archive as knb_archive
import metasalmonpy.knb_publication as knb
from metasalmonpy import publish_sdp_to_knb

_DATA_DIR = os.path.join(os.path.dirname(__file__), "data", "knb")
_R_DIR = os.path.join(_DATA_DIR, "r")


def _extra_available() -> bool:
    try:
        import lxml.etree  # noqa: F401
        import yaml  # noqa: F401 - the sidecar parser lives in the extra
    except ImportError:
        return False
    return True


_REQUIRES_EXTRA = unittest.skipUnless(
    _extra_available(),
    "requires the metasalmonpy[knb] extra (lxml, PyYAML)",
)


def _expected() -> dict:
    with open(os.path.join(_DATA_DIR, "expected.json"), encoding="utf-8") as handle:
        return json.load(handle)


def _r_manifest(name: str = "public") -> dict:
    with open(
        os.path.join(_R_DIR, name, "knb-manifest.json"), encoding="utf-8"
    ) as handle:
        return json.load(handle)


def _canonical_bytes(payload: bytes) -> str:
    return ET.canonicalize(payload.decode("utf-8"), strip_text=True)


def _canonical_file(path: str) -> str:
    return ET.canonicalize(from_file=path, strip_text=True)


def _fixture_sdp(test_case: unittest.TestCase, name: str = "sdp-public") -> str:
    """Copy a fixture SDP into a temp dir so publication can write into it."""
    root = tempfile.mkdtemp()
    test_case.addCleanup(shutil.rmtree, root, True)
    target = os.path.join(root, "sdp")
    shutil.copytree(os.path.join(_DATA_DIR, name), target)
    return target


class _ExplodingAdapter:
    """Every method raises: proof the dry-run path never reaches an adapter."""

    def __getattr__(self, name):
        def explode(*args, **kwargs):
            raise AssertionError(
                f"the dry-run path must never call adapter.{name}"
            )

        return explode


class FakeAdapter:
    """An in-memory DataONE that answers the fourteen era adapter methods."""

    def __init__(
        self,
        subject="https://orcid.org/0000-0001-9317-0364",
        public=True,
        catalog_verified=True,
        anonymous_leak=False,
        checksum_override=None,
        fail_create=False,
        node_id=knb.NODE_ID,
    ):
        self.subject = subject
        self.public = public
        self.catalog_verified = catalog_verified
        self.anonymous_leak = anonymous_leak
        self.checksum_override = checksum_override
        self.fail_create = fail_create
        self.node_id = node_id
        self.store = {}
        self.calls = []

    # -- helpers -----------------------------------------------------------

    def _sysmeta(self, spec, public):
        policy = knb._replication_policy(public)
        return {
            "serial_version": 1,
            "identifier": spec["pid"],
            "format_id": spec["format_id"],
            "size": spec["size"],
            "checksum": spec["sha256"],
            "checksum_algorithm": "SHA-256",
            "submitter": self.subject,
            "rights_holder": self.subject,
            "access": (
                [{"subject": "public", "permission": "read"}] if public else []
            ),
            "replication_allowed": policy["replication_allowed"],
            "number_replicas": policy["number_replicas"],
            "preferred_member_nodes": [],
            "blocked_member_nodes": [],
            "series_id": spec.get("series_id"),
            "media_type": spec["media_type"],
            "file_name": os.path.basename(str(spec["path"])),
            "archived": False,
            "obsoletes": spec.get("obsoletes"),
            "obsoleted_by": spec.get("obsoleted_by"),
            "date_uploaded": "2026-01-01T00:00:00.000+00:00",
            "date_sys_metadata_modified": "2026-01-01T00:00:00.000+00:00",
            "origin_member_node": knb.NODE_ID,
            "authoritative_member_node": knb.NODE_ID,
        }

    def _denied(self):
        return knb.KnbHttpError("anonymous access denied", status=404)

    # -- the fourteen ------------------------------------------------------

    def connect(self, environment, node_id):
        self.calls.append("connect")
        return {"environment": environment, "node_id": node_id}

    def preflight(self, client):
        self.calls.append("preflight")
        return {
            "subject": self.subject,
            "endpoint": knb.MN_ENDPOINT,
            "node_id": self.node_id,
        }

    def list_formats(self, client):
        return [
            "text/csv",
            "application/zip",
            "application/xml",
            "https://eml.ecoinformatics.org/eml-2.2.0",
            knb.ORE_FORMAT_ID,
        ]

    def lookup_system_metadata(self, client, pid):
        entry = self.store.get(pid)
        return None if entry is None else entry["sysmeta"]

    def lookup_series_id(self, client, series_id):
        for entry in self.store.values():
            if entry["sysmeta"].get("series_id") == series_id:
                return entry["sysmeta"]
        return None

    def create_object(self, client, object_spec, subject, public):
        self.calls.append("create_object")
        if self.fail_create:
            raise RuntimeError("upload timed out")
        self.store[object_spec["pid"]] = {
            "bytes": object_spec["bytes"],
            "sysmeta": self._sysmeta(object_spec, public),
        }
        return object_spec["pid"]

    def update_object(self, client, old_pid, object_spec, subject, public):
        self.calls.append("update_object")
        self.store[object_spec["pid"]] = {
            "bytes": object_spec["bytes"],
            "sysmeta": self._sysmeta(object_spec, public),
        }
        if old_pid in self.store:
            self.store[old_pid]["sysmeta"]["obsoleted_by"] = object_spec["pid"]
        return object_spec["pid"]

    def get_bytes(self, client, pid):
        return self.store[pid]["bytes"]

    def get_system_metadata(self, client, pid):
        return self.store[pid]["sysmeta"]

    def get_checksum(self, client, pid, algorithm):
        if self.checksum_override is not None:
            return self.checksum_override
        return self.store[pid]["sysmeta"]["checksum"]

    def get_anonymous_bytes(self, endpoint, pid):
        if not self.public and not self.anonymous_leak:
            raise self._denied()
        return self.store[pid]["bytes"]

    def get_anonymous_system_metadata(self, endpoint, pid):
        if not self.public and not self.anonymous_leak:
            raise self._denied()
        return self.store[pid]["sysmeta"]

    def catalog_lookup(self, client, plan):
        if not self.catalog_verified:
            return []
        documented = [
            obj["pid"]
            for obj in plan["objects"]
            if obj["role"] in ("data", "sdp_archive")
        ]
        docs = []
        for obj in plan["objects"]:
            doc = {"id": obj["pid"]}
            if obj["role"] != "resource_map":
                doc["resourceMap"] = [plan["resource_map_pid"]]
            if obj["pid"] == plan["metadata_pid"]:
                doc["documents"] = documented
            if obj["pid"] in documented:
                doc["isDocumentedBy"] = [plan["metadata_pid"]]
            docs.append(doc)
        return docs

    def anonymous_catalog_lookup(self, plan):
        if self.public:
            return self.catalog_lookup(None, plan)
        if self.anonymous_leak:
            return [{"id": plan["metadata_pid"]}]
        return []


class _AdapterSeam:
    """Install a fake adapter for the duration of a test."""

    def install(self, adapter):
        knb.set_knb_adapter(adapter)
        self.addCleanup(knb.set_knb_adapter, None)
        return adapter


# --- the optional-extra gate ------------------------------------------------------


class KnbExtraGateTests(unittest.TestCase):
    """The gate mirrors R's up-front dependency check for publication."""

    def test_missing_extra_raises_an_actionable_error(self):
        import builtins

        real_import = builtins.__import__

        def blocked(name, *args, **kwargs):
            if name in ("lxml.etree", "lxml", "yaml"):
                raise ImportError(f"blocked {name}")
            return real_import(name, *args, **kwargs)

        builtins.__import__ = blocked
        try:
            with self.assertRaises(ImportError) as caught:
                knb._require_knb_extra()
        finally:
            builtins.__import__ = real_import
        message = str(caught.exception)
        self.assertIn("metasalmonpy[knb]", message)
        self.assertIn("lxml", message)
        self.assertIn("PyYAML", message)


# --- the era adapter boundary -----------------------------------------------------


class KnbAdapterBoundaryTests(unittest.TestCase, _AdapterSeam):
    """The adapter surface must be exactly v0.1.7's fourteen methods."""

    def test_required_methods_are_the_v017_set(self):
        # The era boundary, in R's order. Adding or dropping a method here is
        # a mirror-contract change, not a refactor.
        self.assertEqual(
            knb._required_adapter_methods(),
            (
                "connect",
                "preflight",
                "list_formats",
                "lookup_system_metadata",
                "lookup_series_id",
                "create_object",
                "update_object",
                "get_bytes",
                "get_system_metadata",
                "get_checksum",
                "get_anonymous_bytes",
                "get_anonymous_system_metadata",
                "catalog_lookup",
                "anonymous_catalog_lookup",
            ),
        )

    def test_default_rest_adapter_implements_every_method(self):
        adapter = knb.DataOneRestAdapter()
        knb._validate_adapter(adapter)
        for name in knb._required_adapter_methods():
            self.assertTrue(callable(getattr(adapter, name)), msg=name)

    def test_incomplete_adapter_is_rejected_by_name(self):
        class Partial:
            def connect(self, environment, node_id):
                return None

        with self.assertRaises(ValueError) as caught:
            knb._validate_adapter(Partial())
        message = str(caught.exception)
        self.assertIn("preflight", message)
        self.assertIn("anonymous_catalog_lookup", message)
        self.assertNotIn("connect", message)

    def test_injection_seam_accepts_an_object_or_a_factory(self):
        adapter = FakeAdapter()
        self.install(adapter)
        self.assertIs(knb._adapter(), adapter)

        knb.set_knb_adapter(lambda: adapter)
        self.assertIs(knb._adapter(), adapter)

    def test_default_adapter_only_supports_production_knb(self):
        adapter = knb.DataOneRestAdapter()
        with self.assertRaises(ValueError):
            adapter.connect("STAGING", knb.NODE_ID)
        with self.assertRaises(ValueError):
            adapter.connect(knb.ENVIRONMENT, "urn:node:mnTestKNB")

    def test_rest_adapter_refuses_work_before_preflight(self):
        adapter = knb.DataOneRestAdapter()
        client = adapter.connect(knb.ENVIRONMENT, knb.NODE_ID)
        with self.assertRaises(ValueError):
            adapter.get_bytes(client, "urn:uuid:abc")


# --- pure-helper parity with R ------------------------------------------------------


class KnbHelperParityTests(unittest.TestCase):
    """Every pure helper returns exactly what metasalmon v0.1.7 returned."""

    def setUp(self):
        self.expected = _expected()
        self.helpers = self.expected["helpers"]
        self.extra = self.expected["extra"]

    def test_constants_match(self):
        self.assertEqual(knb.ORE_PROFILE, self.helpers["ore_profile"])
        self.assertEqual(knb.MN_ENDPOINT, self.helpers["mn_endpoint"])
        self.assertEqual(knb.RESOLVER, self.helpers["resolver"])
        self.assertEqual(knb.ENVIRONMENT, "PROD")
        self.assertEqual(knb.NODE_ID, "urn:node:KNB")

    def test_replication_policy_matches(self):
        self.assertEqual(
            knb._replication_policy(True), self.helpers["replication_public"]
        )
        self.assertEqual(
            knb._replication_policy(False), self.helpers["replication_private"]
        )
        with self.assertRaises(ValueError):
            knb._replication_policy(None)

    def test_require_replication_policy_is_fail_closed(self):
        knb._require_replication_policy(knb._replication_policy(False), False)
        with self.assertRaises(ValueError):
            knb._require_replication_policy(knb._replication_policy(True), False)

    def test_hash_and_url_helpers_match(self):
        self.assertEqual(knb._sha256_text("demo"), self.helpers["sha256_text_demo"])
        self.assertEqual(
            knb._resolve_url("urn:uuid:abc"), self.helpers["resolve_url_demo"]
        )

    def test_resource_map_pid_matches_r_for_a_synthetic_membership(self):
        # A pure UUIDv5 over the exact member table; drift in any field or in
        # the ordering changes the value.
        members = [
            {
                "role": "data",
                "path": "data/counts.csv",
                "pid": "urn:uuid:22222222-2222-5222-8222-222222222222",
                "format_id": "text/csv",
                "size": 87,
                "sha256": "a" * 64,
            },
            {
                "role": "metadata",
                "path": "metadata/eml.xml",
                "pid": "urn:uuid:11111111-1111-5111-8111-111111111111",
                "format_id": "https://eml.ecoinformatics.org/eml-2.2.0",
                "size": 42,
                "sha256": "b" * 64,
            },
        ]
        self.assertEqual(
            knb._resource_map_pid(
                "urn:uuid:11111111-1111-5111-8111-111111111111",
                "2026-01-01",
                members,
            ),
            self.helpers["resource_map_pid_demo"],
        )

    def test_redaction_matches(self):
        self.assertEqual(
            knb._redact("Authorization: Bearer abc.def-ghi_jkl"),
            self.helpers["redact_bearer"],
        )
        self.assertEqual(
            knb._redact("token eyJhbGciOi.eyJzdWIi.c2ln here"),
            self.helpers["redact_jwt"],
        )
        self.assertEqual(
            knb._redact("dataone_token=secretvalue trailing"),
            self.helpers["redact_option"],
        )

    def test_orcid_and_subject_matching_match(self):
        self.assertEqual(
            knb._orcid_key("https://ORCID.org/0000-0001-9317-0364/"),
            self.helpers["orcid_key"],
        )
        same = self.extra["same_subject"]
        self.assertEqual(knb._same_subject("a", "a"), same["exact"])
        self.assertEqual(
            knb._same_subject(
                "https://orcid.org/0000-0001-9317-0364",
                "http://ORCID.org/0000-0001-9317-0364/",
            ),
            same["orcid_case"],
        )
        self.assertEqual(
            knb._same_subject(
                "https://orcid.org/0000-0001-9317-0364",
                "https://orcid.org/0000-0002-1825-0097",
            ),
            same["different"],
        )
        self.assertEqual(knb._same_subject("", "a"), same["empty"])

    def test_status_ranks_match(self):
        for status, rank in self.helpers["status_ranks"].items():
            key = "nope" if status == "unknown" else status
            self.assertEqual(knb._status_rank(key), rank, msg=status)
        self.assertEqual(knb._advance_status("complete", "dry_run"), "complete")
        self.assertEqual(knb._advance_status("dry_run", "pending"), "pending")

    def test_timestamp_validation_matches(self):
        stamps = self.helpers["valid_timestamps"]
        self.assertEqual(
            knb._valid_timestamp("2026-01-01T00:00:00Z"), stamps["z"]
        )
        self.assertEqual(
            knb._valid_timestamp("2026-01-01T00:00:00.123+00:00"),
            stamps["offset"],
        )
        self.assertEqual(
            knb._valid_timestamp("2026-01-01 00:00:00"), stamps["naive"]
        )
        self.assertEqual(knb._valid_timestamp(""), stamps["empty"])

    def test_solr_quoting_and_catalog_url_match(self):
        self.assertEqual(knb._solr_quote('a"b\\c'), self.helpers["solr_quote"])
        manifest = _r_manifest()
        plan = {
            "objects": manifest["objects"],
            "resource_map_pid": manifest["resource_map_pid"],
            "metadata_pid": manifest["metadata_pid"],
        }
        self.assertEqual(knb._catalog_url(plan), self.helpers["catalog_url"])

    def test_access_policy_normalization_matches(self):
        expected = [
            (row["subject"], row["permission"])
            for row in self.extra["normalized_access"]
        ]
        self.assertEqual(
            knb._normalize_access(
                [
                    {"subject": "public", "permission": "READ"},
                    {
                        "subject": "https://orcid.org/0000-0001-9317-0364",
                        "permission": "write",
                    },
                    {"subject": "public", "permission": "read"},
                ]
            ),
            expected,
        )
        self.assertEqual(knb._normalize_access(None), [])
        with self.assertRaises(ValueError):
            knb._normalize_access([{"subject": "public"}])

    def test_echo_subjects_matches(self):
        # Only server-verified identities count; an unverified person and the
        # equivalent identities of an unverified person are both dropped.
        credentials = [
            (
                "person",
                [
                    ("subject", "https://orcid.org/0000-0001-9317-0364"),
                    ("verified", "true"),
                    ("equivalentIdentity", "CN=alex,DC=dataone,DC=org"),
                ],
            ),
            (
                "person",
                [
                    ("subject", "https://orcid.org/0000-0002-1825-0097"),
                    ("verified", "false"),
                ],
            ),
            ("person", [("subject", "CN=anon,DC=dataone,DC=org")]),
        ]
        self.assertEqual(
            knb._echo_subjects(credentials), self.extra["echo_subjects"]
        )

    def test_server_verified_subject_requires_an_echo(self):
        credentials = [
            (
                "person",
                [
                    ("subject", "https://orcid.org/0000-0001-9317-0364"),
                    ("verified", "true"),
                ],
            )
        ]
        self.assertEqual(
            knb._server_verified_subject(
                credentials, "http://orcid.org/0000-0001-9317-0364/"
            ),
            "https://orcid.org/0000-0001-9317-0364",
        )
        with self.assertRaises(ValueError):
            knb._server_verified_subject(
                credentials, "https://orcid.org/0000-0002-1825-0097"
            )

    def test_legacy_sdp_artifact_objects_match(self):
        # The expanded representation is no longer planned at 0.1.7, but its
        # identifiers must stay stable so old manifests remain auditable.
        sdp = os.path.join(_DATA_DIR, "sdp-public")
        for expected in self.extra["sdp_artifact_objects"]:
            actual = knb._sdp_artifact_object(
                os.path.join(sdp, expected["path"]), sdp, "demo-salmon-2026"
            )
            for field in (
                "role",
                "path",
                "pid",
                "format_id",
                "media_type",
                "size",
                "sha256",
            ):
                self.assertEqual(actual[field], expected[field], msg=field)

    def test_lookup_http_status_leaves_nothing_ambiguous(self):
        self.assertEqual(knb._lookup_http_status(200, "x", "PID"), "present")
        self.assertEqual(knb._lookup_http_status(404, "x", "PID"), "absent")
        with self.assertRaises(ValueError):
            knb._lookup_http_status(503, "x", "PID")


# --- exact planner parity with R ----------------------------------------------------


class KnbPlannerParityTests(unittest.TestCase):
    """Drive the planner from R's own member table and match it exactly.

    The archive ZIP and the EML document are byte-different by construction
    (PARITY.md 4, 15, 17), so the end-to-end Python plan cannot reproduce R's
    hashes. Feeding R's member table isolates every algorithm that *is*
    byte-exact: the resource-map PID, the ORE graph, the fingerprint payload
    encoding, the fingerprint itself, and the manifest JSON.
    """

    def setUp(self):
        self.manifest = _r_manifest()
        self.members = [
            obj
            for obj in self.manifest["objects"]
            if obj["role"] != "resource_map"
        ]

    def test_resource_map_pid_matches_r(self):
        self.assertEqual(
            knb._resource_map_pid(
                self.manifest["package_id"], "2026-01-01", self.members
            ),
            self.manifest["resource_map_pid"],
        )

    def test_ore_document_matches_r(self):
        ore = knb._build_ore(
            self.manifest["resource_map_pid"],
            self.manifest["package_id"],
            "2026-01-01",
            self.members,
        )
        knb._validate_ore(ore, self.manifest["resource_map_pid"], self.members)
        self.assertEqual(
            _canonical_bytes(knb._xml_bytes(ore)),
            _canonical_file(os.path.join(_R_DIR, "public", "resource-map.rdf")),
        )

    def test_ore_validation_rejects_a_tampered_graph(self):
        ore = knb._build_ore(
            self.manifest["resource_map_pid"],
            self.manifest["package_id"],
            "2026-01-01",
            self.members,
        )
        for node in knb._find_all_local(ore, "aggregates"):
            node.set("rdf:resource", knb._resolve_url("urn:uuid:not-planned"))
            break
        with self.assertRaises(ValueError):
            knb._validate_ore(
                ore, self.manifest["resource_map_pid"], self.members
            )

    def test_fingerprint_payload_bytes_match_r(self):
        # plan_sha256 hashes these exact bytes; a JSON-encoding difference
        # would silently invalidate every reviewed manifest.
        with open(
            os.path.join(_R_DIR, "public", "plan-fingerprint-payload.json"), "rb"
        ) as handle:
            payload = handle.read()
        self.assertEqual(knb._json_bytes(json.loads(payload)), payload)
        self.assertEqual(
            knb._sha256_raw(payload), self.manifest["plan_sha256"]
        )

    def test_plan_fingerprint_matches_r(self):
        self.assertEqual(
            knb._plan_fingerprint(self.manifest), self.manifest["plan_sha256"]
        )
        self.assertEqual(
            knb._manifest_fingerprint(self.manifest),
            self.manifest["plan_sha256"],
        )

    def test_private_plan_fingerprint_matches_r(self):
        private = _r_manifest("private")
        self.assertEqual(
            knb._plan_fingerprint(private), private["plan_sha256"]
        )
        # Same objects, different access decision: the fingerprint must move.
        self.assertNotEqual(
            private["plan_sha256"], self.manifest["plan_sha256"]
        )

    def test_schema_version_2_fingerprint_matches_r(self):
        with open(
            os.path.join(_R_DIR, "public", "knb-manifest-v2.json"),
            encoding="utf-8",
        ) as handle:
            legacy = json.load(handle)
        self.assertEqual(
            knb._manifest_fingerprint(legacy),
            _expected()["extra"]["manifest_v2_plan_sha256"],
        )
        self.assertEqual(
            knb._manifest_fingerprint(legacy), legacy["plan_sha256"]
        )

    def test_manifest_bytes_match_r(self):
        with open(
            os.path.join(_R_DIR, "public", "knb-manifest.json"), "rb"
        ) as handle:
            payload = handle.read()
        built = knb._manifest(self.manifest, status="dry_run")
        self.assertEqual(knb._json_bytes(built), payload)

    def test_manifest_carries_previous_object_state_and_status(self):
        previous = knb._manifest(self.manifest, status="dry_run")
        previous["status"] = "complete"
        for obj in previous["objects"]:
            obj["state"] = "verified"
        previous["catalog_verified"] = True
        rebuilt = knb._manifest(
            self.manifest, status="dry_run", previous=previous
        )
        # A durable status never regresses and verified objects stay verified.
        self.assertEqual(rebuilt["status"], "complete")
        self.assertTrue(
            all(obj["state"] == "verified" for obj in rebuilt["objects"])
        )
        self.assertTrue(rebuilt["catalog_verified"])

    def test_system_metadata_documents_match_r(self):
        subject = self.manifest["expected_subject"]
        for obj in self.manifest["objects"]:
            spec = dict(obj)
            spec["series_id"] = (
                self.manifest["series_id"] if obj["role"] == "metadata" else None
            )
            for public in (True, False):
                document = knb._system_metadata_document(
                    spec,
                    subject,
                    public,
                    knb.NODE_ID,
                    knb._replication_policy(public),
                )
                label = ("public-" if public else "private-") + obj["role"]
                self.assertEqual(
                    _canonical_bytes(knb._xml_bytes(document)),
                    _canonical_file(
                        os.path.join(_R_DIR, "sysmeta", label + ".xml")
                    ),
                    msg=label,
                )

    def test_revision_system_metadata_matches_r(self):
        metadata = [
            obj for obj in self.manifest["objects"] if obj["role"] == "metadata"
        ][0]
        spec = dict(metadata)
        spec["series_id"] = self.manifest["series_id"]
        spec["obsoletes"] = "urn:uuid:00000000-0000-5000-8000-000000000001"
        document = knb._system_metadata_document(
            spec,
            self.manifest["expected_subject"],
            False,
            knb.NODE_ID,
            knb._replication_policy(False),
        )
        self.assertEqual(
            _canonical_bytes(knb._xml_bytes(document)),
            _canonical_file(
                os.path.join(_R_DIR, "sysmeta", "private-metadata-revision.xml")
            ),
        )

    def test_system_metadata_parser_matches_r(self):
        with open(
            os.path.join(_R_DIR, "sysmeta", "server-response.xml"), "rb"
        ) as handle:
            payload = handle.read()
        with open(
            os.path.join(_R_DIR, "sysmeta", "server-response-parsed.json"),
            encoding="utf-8",
        ) as handle:
            expected = json.load(handle)
        self.assertEqual(knb._parse_system_metadata(payload), expected)

    def test_system_metadata_validation_accepts_the_parsed_response(self):
        remote = knb._parse_system_metadata(
            open(
                os.path.join(_R_DIR, "sysmeta", "server-response.xml"), "rb"
            ).read()
        )
        data_object = [
            obj for obj in self.manifest["objects"] if obj["role"] == "data"
        ][0]
        # metasalmon requires an explicit archived state, exactly as R does: a
        # document that omits <archived> parses to None and is a collision.
        with self.assertRaises(ValueError) as caught:
            knb._validate_system_metadata(
                remote,
                data_object,
                self.manifest["expected_subject"],
                True,
                knb._replication_policy(True),
            )
        self.assertIn("archived", str(caught.exception))

        remote["archived"] = False
        knb._validate_system_metadata(
            remote,
            data_object,
            self.manifest["expected_subject"],
            True,
            knb._replication_policy(True),
        )
        # The same document is a collision for a private plan: the access
        # policy and replication policy are part of the reviewed contract.
        with self.assertRaises(ValueError):
            knb._validate_system_metadata(
                remote,
                data_object,
                self.manifest["expected_subject"],
                False,
                knb._replication_policy(False),
            )

    def test_system_metadata_validation_reports_the_colliding_field(self):
        remote = knb._parse_system_metadata(
            open(
                os.path.join(_R_DIR, "sysmeta", "server-response.xml"), "rb"
            ).read()
        )
        remote["checksum"] = "0" * 64
        data_object = [
            obj for obj in self.manifest["objects"] if obj["role"] == "data"
        ][0]
        with self.assertRaises(ValueError) as caught:
            knb._validate_system_metadata(
                remote,
                data_object,
                self.manifest["expected_subject"],
                True,
                knb._replication_policy(True),
            )
        self.assertIn("checksum", str(caught.exception))


# --- the deterministic SDP archive ---------------------------------------------------


class KnbArchiveTests(unittest.TestCase):
    """The ZIP is contract-parity with R: closed inventory, radix order."""

    def test_archive_members_match_r_exactly(self):
        sdp = _fixture_sdp(self)
        archive = knb_archive._write_sdp_archive(sdp)
        expected = _expected()["archive"]
        self.assertEqual(archive["members"], expected["members"])
        self.assertEqual(archive["file_name"], expected["file_name"])
        self.assertEqual(archive["dataset_id"], expected["dataset_id"])
        self.assertEqual(archive["format_id"], expected["format_id"])
        self.assertEqual(archive["media_type"], expected["media_type"])

    def test_archive_is_byte_reproducible_under_the_python_reference(self):
        # R pins zip 3.0.1 for the same reason: the checksum is an immutable
        # DataONE PID input, so a compressor change must be reviewed.
        first = knb_archive._write_sdp_archive(_fixture_sdp(self))
        second = knb_archive._write_sdp_archive(_fixture_sdp(self))
        self.assertEqual(first["sha256"], second["sha256"])
        self.assertEqual(
            first["sha256"], _expected()["python_archive"]["sha256"]
        )
        self.assertEqual(
            knb_archive.ARCHIVE_DETERMINISM_REFERENCE,
            _expected()["python_archive"]["determinism_reference"],
        )

    def test_archive_member_bytes_are_the_source_bytes(self):
        import zipfile

        sdp = _fixture_sdp(self)
        archive = knb_archive._write_sdp_archive(sdp)
        with zipfile.ZipFile(archive["path"]) as handle:
            self.assertEqual(handle.namelist(), _expected()["archive"]["members"])
            for info in handle.infolist():
                self.assertEqual(info.date_time, (2000, 1, 1, 0, 0, 0))
                self.assertEqual(info.external_attr >> 16, 0o644)
                with open(
                    os.path.join(sdp, *info.filename.split("/")), "rb"
                ) as source:
                    self.assertEqual(handle.read(info.filename), source.read())

    def test_archive_never_contains_eml_or_publication_artifacts(self):
        archive = knb_archive._write_sdp_archive(_fixture_sdp(self))
        self.assertNotIn("metadata/eml.xml", archive["members"])
        self.assertFalse(
            any(
                member.startswith("publication/")
                for member in archive["members"]
            )
        )

    def test_reserved_paths_are_refused_by_the_inventory_validator(self):
        for reserved in ("metadata/eml.xml", "publication/receipt.json"):
            with self.assertRaises(ValueError):
                knb_archive._sdp_archive_validate_relative(reserved)
        for malformed in ("/abs/path.csv", "a//b.csv", "data/", "../x.csv"):
            with self.assertRaises(ValueError):
                knb_archive._sdp_archive_validate_relative(malformed)

    def test_missing_required_artifact_fails_closed(self):
        sdp = _fixture_sdp(self)
        os.remove(os.path.join(sdp, "metadata", "codes.csv"))
        with self.assertRaises(FileNotFoundError):
            knb_archive._sdp_archive_inventory(sdp)

    def test_symlinked_member_is_refused(self):
        sdp = _fixture_sdp(self)
        target = os.path.join(sdp, "metadata", "codes.csv")
        elsewhere = os.path.join(os.path.dirname(sdp), "codes.csv")
        shutil.move(target, elsewhere)
        os.symlink(elsewhere, target)
        with self.assertRaises(ValueError):
            knb_archive._sdp_archive_inventory(sdp)

    def test_existing_archive_with_different_bytes_needs_overwrite(self):
        sdp = _fixture_sdp(self)
        archive = knb_archive._write_sdp_archive(sdp)
        with open(archive["path"], "ab") as handle:
            handle.write(b"tampered")
        with self.assertRaises(ValueError):
            knb_archive._write_sdp_archive(sdp)
        replaced = knb_archive._write_sdp_archive(sdp, overwrite=True)
        self.assertEqual(replaced["sha256"], archive["sha256"])

    def test_identical_archive_rewrite_is_idempotent(self):
        sdp = _fixture_sdp(self)
        first = knb_archive._write_sdp_archive(sdp)
        again = knb_archive._write_sdp_archive(sdp)
        self.assertEqual(first["sha256"], again["sha256"])

    def test_output_must_stay_under_publication(self):
        sdp = _fixture_sdp(self)
        with self.assertRaises(ValueError):
            knb_archive._write_sdp_archive(
                sdp, output_path=os.path.join(sdp, "data", "sdp.zip")
            )
        with self.assertRaises(ValueError):
            knb_archive._write_sdp_archive(
                sdp, output_path=os.path.join(sdp, "publication", "sdp.tar")
            )

    def test_archive_filename_slug_matches_r(self):
        self.assertEqual(
            knb_archive._sdp_archive_filename("demo-salmon-2026"),
            _expected()["helpers"]["archive_filename"],
        )
        self.assertEqual(
            knb_archive._sdp_archive_filename("Demo Salmon 2026!!"),
            _expected()["extra"]["archive_filename_slug"],
        )
        with self.assertRaises(ValueError):
            knb_archive._sdp_archive_filename("   ")


# --- the dry-run planning path -------------------------------------------------------


@_REQUIRES_EXTRA
class KnbDryRunTests(unittest.TestCase, _AdapterSeam):
    """The default is credential-free, network-free, and fail-closed."""

    def test_dry_run_never_constructs_an_adapter(self):
        # R's sentinel: an adapter whose every method raises proves the
        # planning path is independent of DataONE credentials.
        self.install(_ExplodingAdapter())
        sdp = _fixture_sdp(self)
        result = publish_sdp_to_knb(sdp, public=True, dry_run=True)
        self.assertEqual(result["status"], "dry_run")

    def test_dry_run_writes_the_expected_plan_shape(self):
        sdp = _fixture_sdp(self)
        result = publish_sdp_to_knb(sdp, public=True, dry_run=True)
        expected = _expected()["public"]

        # Identifiers that do not depend on formatter or compressor bytes are
        # exactly R's.
        self.assertEqual(result["package_id"], expected["package_id"])
        self.assertEqual(result["series_id"], expected["series_id"])

        manifest = result["manifest"]
        self.assertEqual(manifest["schema_version"], 3)
        self.assertEqual(manifest["status"], "dry_run")
        self.assertEqual(manifest["environment"], "PROD")
        self.assertEqual(manifest["node_id"], "urn:node:KNB")
        self.assertEqual(manifest["representation"], "archive")
        self.assertEqual(
            manifest["replication_policy"], knb._replication_policy(True)
        )
        self.assertEqual(
            [obj["role"] for obj in manifest["objects"]],
            ["data", "sdp_archive", "metadata", "resource_map"],
        )
        self.assertTrue(
            all(obj["state"] == "planned" for obj in manifest["objects"])
        )
        self.assertFalse(manifest["catalog_verified"])
        self.assertEqual(
            manifest["plan_sha256"], knb._plan_fingerprint(manifest)
        )
        self.assertTrue(os.path.isfile(result["resource_map_path"]))
        self.assertTrue(os.path.isfile(result["sdp_archive_path"]))

    def test_dry_run_ore_is_structurally_identical_to_r(self):
        # Only the archive and EML checksums differ, so the graph shape,
        # ordering and predicates must match R's exactly.
        sdp = _fixture_sdp(self)
        result = publish_sdp_to_knb(sdp, public=True, dry_run=True)
        mine = ET.parse(result["resource_map_path"]).getroot()
        theirs = ET.parse(
            os.path.join(_R_DIR, "public", "resource-map.rdf")
        ).getroot()

        def shape(root):
            return [
                (
                    knb._local_name(node.tag),
                    sorted(knb._local_name(key) for key in node.attrib),
                )
                for node in root.iter()
            ]

        self.assertEqual(shape(mine), shape(theirs))

    def test_dry_run_is_deterministic_across_runs(self):
        first = publish_sdp_to_knb(_fixture_sdp(self), public=True, dry_run=True)
        second = publish_sdp_to_knb(_fixture_sdp(self), public=True, dry_run=True)
        self.assertEqual(
            first["manifest"]["plan_sha256"],
            second["manifest"]["plan_sha256"],
        )
        self.assertEqual(
            first["resource_map_pid"], second["resource_map_pid"]
        )

    def test_rerunning_a_dry_run_in_place_is_idempotent(self):
        sdp = _fixture_sdp(self)
        first = publish_sdp_to_knb(sdp, public=True, dry_run=True)
        again = publish_sdp_to_knb(sdp, public=True, dry_run=True)
        self.assertEqual(
            first["manifest"]["plan_sha256"], again["manifest"]["plan_sha256"]
        )

    def test_private_plan_differs_from_the_public_plan(self):
        public = publish_sdp_to_knb(_fixture_sdp(self), public=True, dry_run=True)
        private = publish_sdp_to_knb(
            _fixture_sdp(self, "sdp-private"), public=False, dry_run=True
        )
        self.assertEqual(
            private["manifest"]["replication_policy"],
            knb._replication_policy(False),
        )
        self.assertNotEqual(
            public["manifest"]["plan_sha256"],
            private["manifest"]["plan_sha256"],
        )

    def test_access_must_be_explicit_and_match_the_reviewed_sidecar(self):
        sdp = _fixture_sdp(self)
        with self.assertRaises(ValueError):
            publish_sdp_to_knb(sdp, dry_run=True)
        with self.assertRaises(ValueError):
            publish_sdp_to_knb(sdp, public="yes", dry_run=True)
        # The sidecar says public: yes; planning private must refuse.
        with self.assertRaises(ValueError):
            publish_sdp_to_knb(sdp, public=False, dry_run=True)

    def test_missing_required_artifact_fails_closed(self):
        sdp = _fixture_sdp(self)
        os.remove(os.path.join(sdp, "metadata", "codes.csv"))
        with self.assertRaises(Exception):
            publish_sdp_to_knb(sdp, public=True, dry_run=True)

    def test_missing_semantic_review_ledger_fails_closed(self):
        sdp = _fixture_sdp(self)
        os.remove(os.path.join(sdp, "reviewed_semantic_selections.csv"))
        with self.assertRaises(Exception):
            publish_sdp_to_knb(sdp, public=True, dry_run=True)

    def test_review_candidate_annotations_are_refused(self):
        sdp = _fixture_sdp(self)
        vocabulary_path = os.path.join(
            sdp, "metadata", "semantic_vocabulary.csv"
        )
        vocabulary = pd.read_csv(vocabulary_path, dtype=str, keep_default_na=False)
        vocabulary.loc[0, "source"] = "review-candidate"
        vocabulary.to_csv(vocabulary_path, index=False)
        with self.assertRaises(ValueError) as caught:
            publish_sdp_to_knb(sdp, public=True, dry_run=True)
        self.assertIn("review-candidate", str(caught.exception))

    def test_a_changed_plan_cannot_reuse_an_existing_manifest(self):
        # DataONE PIDs are immutable; a second plan at the same manifest path
        # must be refused rather than silently re-minted.
        sdp = _fixture_sdp(self)
        publish_sdp_to_knb(sdp, public=True, dry_run=True)
        with open(os.path.join(sdp, "data", "counts.csv"), "a") as handle:
            handle.write("row-9,2026,9,,\n")
        with self.assertRaises(Exception):
            publish_sdp_to_knb(sdp, public=True, dry_run=True)

    def test_dot_segments_in_supplied_paths_are_refused(self):
        sdp = _fixture_sdp(self)
        with self.assertRaises(ValueError):
            publish_sdp_to_knb(
                sdp,
                public=True,
                dry_run=True,
                eml_path=os.path.join(sdp, "metadata", "..", "eml.xml"),
            )

    def test_artifacts_outside_the_package_are_refused(self):
        sdp = _fixture_sdp(self)
        outside = os.path.join(os.path.dirname(sdp), "knb-manifest.json")
        with self.assertRaises(ValueError):
            publish_sdp_to_knb(
                sdp, public=True, dry_run=True, manifest_path=outside
            )


# --- the live state machine ------------------------------------------------------------


@_REQUIRES_EXTRA
class KnbLivePublicationTests(unittest.TestCase, _AdapterSeam):
    """Live publication mutates only behind an approved, reviewed plan."""

    def _reviewed(self, name="sdp-public", public=True):
        sdp = _fixture_sdp(self, name)
        publish_sdp_to_knb(sdp, public=public, dry_run=True)
        return sdp

    def test_live_requires_explicit_confirmation(self):
        sdp = self._reviewed()
        self.install(_ExplodingAdapter())
        with self.assertRaises(ValueError) as caught:
            publish_sdp_to_knb(sdp, public=True, dry_run=False)
        self.assertIn("confirm=True", str(caught.exception))
        with self.assertRaises(ValueError):
            publish_sdp_to_knb(sdp, public=True, dry_run=False, confirm=False)

    def test_live_requires_a_pre_existing_reviewed_manifest(self):
        sdp = _fixture_sdp(self)
        self.install(_ExplodingAdapter())
        with self.assertRaises(ValueError) as caught:
            publish_sdp_to_knb(
                sdp, public=True, dry_run=False, confirm=True
            )
        self.assertIn("pre-existing", str(caught.exception))

    def test_public_publication_verifies_every_object(self):
        sdp = self._reviewed()
        adapter = self.install(FakeAdapter(public=True))
        result = publish_sdp_to_knb(
            sdp, public=True, dry_run=False, confirm=True
        )
        self.assertEqual(result["status"], "published")
        manifest = result["manifest"]
        self.assertEqual(manifest["status"], "complete")
        self.assertTrue(manifest["catalog_verified"])
        self.assertTrue(
            all(obj["state"] == "verified" for obj in manifest["objects"])
        )
        self.assertEqual(len(adapter.store), 4)
        # The persisted manifest is the durable record, not just the return.
        with open(result["manifest_path"], encoding="utf-8") as handle:
            self.assertEqual(json.load(handle)["status"], "complete")

    def test_private_publication_proves_anonymous_non_disclosure(self):
        sdp = self._reviewed("sdp-private", public=False)
        adapter = self.install(FakeAdapter(public=False))
        result = publish_sdp_to_knb(
            sdp, public=False, dry_run=False, confirm=True
        )
        self.assertEqual(result["status"], "published")
        self.assertTrue(result["manifest"]["catalog_verified"])
        self.assertEqual(len(adapter.store), 4)

    def test_private_publication_fails_when_anonymous_access_leaks(self):
        sdp = self._reviewed("sdp-private", public=False)
        self.install(FakeAdapter(public=False, anonymous_leak=True))
        with self.assertRaises(RuntimeError) as caught:
            publish_sdp_to_knb(sdp, public=False, dry_run=False, confirm=True)
        self.assertIn("KNB publication failed", str(caught.exception))

    def test_checksum_mismatch_aborts_before_completion(self):
        sdp = self._reviewed()
        self.install(FakeAdapter(public=True, checksum_override="0" * 64))
        with self.assertRaises(RuntimeError) as caught:
            publish_sdp_to_knb(sdp, public=True, dry_run=False, confirm=True)
        self.assertIn("checksum", str(caught.exception))
        with open(
            os.path.join(sdp, "publication", "knb-manifest.json"),
            encoding="utf-8",
        ) as handle:
            self.assertNotEqual(json.load(handle)["status"], "complete")

    def test_unverified_catalog_stops_at_published_pending_catalog(self):
        sdp = self._reviewed()
        self.install(FakeAdapter(public=True, catalog_verified=False))
        result = publish_sdp_to_knb(
            sdp, public=True, dry_run=False, confirm=True
        )
        self.assertEqual(result["status"], "published_pending_catalog")
        self.assertFalse(result["manifest"]["catalog_verified"])
        # A partial success is never reported as complete.
        with open(result["manifest_path"], encoding="utf-8") as handle:
            self.assertEqual(
                json.load(handle)["status"], "published_pending_catalog"
            )

    def test_subject_mismatch_aborts(self):
        sdp = self._reviewed()
        self.install(
            FakeAdapter(subject="https://orcid.org/0000-0002-1825-0097")
        )
        with self.assertRaises(RuntimeError) as caught:
            publish_sdp_to_knb(sdp, public=True, dry_run=False, confirm=True)
        self.assertIn("KNB publication failed", str(caught.exception))

    def test_node_mismatch_aborts(self):
        sdp = self._reviewed()
        self.install(FakeAdapter(node_id="urn:node:mnTestKNB"))
        with self.assertRaises(RuntimeError):
            publish_sdp_to_knb(sdp, public=True, dry_run=False, confirm=True)

    def test_missing_format_registration_aborts_before_any_create(self):
        sdp = self._reviewed()
        adapter = FakeAdapter(public=True)
        adapter.list_formats = lambda client: ["text/csv"]
        self.install(adapter)
        with self.assertRaises(RuntimeError):
            publish_sdp_to_knb(sdp, public=True, dry_run=False, confirm=True)
        self.assertEqual(adapter.store, {})

    def test_a_failed_create_is_resolved_by_an_authoritative_lookup(self):
        # A timed-out create may have committed; only a follow-up lookup can
        # resolve that, and an unresolved failure must re-raise.
        sdp = self._reviewed()
        adapter = FakeAdapter(public=True, fail_create=True)
        self.install(adapter)
        with self.assertRaises(RuntimeError) as caught:
            publish_sdp_to_knb(sdp, public=True, dry_run=False, confirm=True)
        self.assertIn("upload timed out", str(caught.exception))

    def test_adapter_warnings_become_errors(self):
        import warnings

        sdp = self._reviewed()
        adapter = FakeAdapter(public=True)
        original = adapter.list_formats

        def noisy(client):
            warnings.warn("token nearly expired", UserWarning)
            return original(client)

        adapter.list_formats = noisy
        self.install(adapter)
        with self.assertRaises(RuntimeError) as caught:
            publish_sdp_to_knb(sdp, public=True, dry_run=False, confirm=True)
        self.assertIn("Live KNB adapter warning", str(caught.exception))

    def test_failure_messages_are_redacted(self):
        sdp = self._reviewed()
        adapter = FakeAdapter(public=True)

        def leaky(client):
            raise RuntimeError(
                "upstream said Authorization: Bearer supersecrettoken"
            )

        adapter.list_formats = leaky
        self.install(adapter)
        with self.assertRaises(RuntimeError) as caught:
            publish_sdp_to_knb(sdp, public=True, dry_run=False, confirm=True)
        message = str(caught.exception)
        self.assertNotIn("supersecrettoken", message)
        self.assertIn("[REDACTED]", message)

    def test_a_second_live_run_reports_already_published(self):
        sdp = self._reviewed()
        adapter = self.install(FakeAdapter(public=True))
        publish_sdp_to_knb(sdp, public=True, dry_run=False, confirm=True)
        again = publish_sdp_to_knb(
            sdp, public=True, dry_run=False, confirm=True
        )
        self.assertEqual(again["status"], "already_published")
        self.assertEqual(len(adapter.store), 4)


# --- immutable revisions ----------------------------------------------------------------


@_REQUIRES_EXTRA
class KnbRevisionTests(unittest.TestCase, _AdapterSeam):
    """A revision mints new PIDs in a stable series, in a fresh directory."""

    def _verified_manifest(self, sdp: str) -> str:
        publish_sdp_to_knb(sdp, public=True, dry_run=True)
        manifest_path = os.path.join(sdp, "publication", "knb-manifest.json")
        with open(manifest_path, encoding="utf-8") as handle:
            manifest = json.load(handle)
        manifest["status"] = "complete"
        for obj in manifest["objects"]:
            obj["state"] = "verified"
        with open(manifest_path, "w", encoding="utf-8") as handle:
            handle.write(knb._json_bytes(manifest).decode("utf-8"))
        return manifest_path

    def _revised_sdp(self, revision_key="private-review-2") -> str:
        import yaml

        sdp = _fixture_sdp(self)
        mapping_path = os.path.join(sdp, "metadata", "eml-mapping.yml")
        with open(mapping_path, encoding="utf-8") as handle:
            mapping = yaml.safe_load(handle)
        mapping["publication"]["revision_key"] = revision_key
        with open(mapping_path, "w", encoding="utf-8") as handle:
            yaml.safe_dump(mapping, handle, sort_keys=False)
        return sdp

    def test_revision_obsoletes_its_predecessor_in_the_same_series(self):
        prior_sdp = _fixture_sdp(self)
        prior_manifest_path = self._verified_manifest(prior_sdp)
        with open(prior_manifest_path, encoding="utf-8") as handle:
            prior = json.load(handle)

        revised = self._revised_sdp()
        self.install(_ExplodingAdapter())
        result = publish_sdp_to_knb(
            revised,
            public=True,
            dry_run=True,
            revision_manifest=prior_manifest_path,
        )

        self.assertEqual(result["series_id"], prior["series_id"])
        self.assertNotEqual(result["package_id"], prior["package_id"])
        self.assertNotEqual(
            result["resource_map_pid"], prior["resource_map_pid"]
        )
        objects = {obj["role"]: obj for obj in result["manifest"]["objects"]}
        self.assertEqual(
            objects["metadata"]["obsoletes"], prior["metadata_pid"]
        )
        self.assertEqual(
            objects["resource_map"]["obsoletes"], prior["resource_map_pid"]
        )
        self.assertEqual(
            result["manifest"]["revision_of"]["plan_sha256"],
            prior["plan_sha256"],
        )

    def test_revision_requires_a_fresh_package_directory(self):
        sdp = _fixture_sdp(self)
        manifest_path = self._verified_manifest(sdp)
        with self.assertRaises(ValueError) as caught:
            publish_sdp_to_knb(
                sdp, public=True, dry_run=True, revision_manifest=manifest_path
            )
        self.assertIn("fresh versioned SDP directory", str(caught.exception))

    def test_revision_requires_a_new_revision_key(self):
        prior_sdp = _fixture_sdp(self)
        manifest_path = self._verified_manifest(prior_sdp)
        unchanged = _fixture_sdp(self)
        with self.assertRaises(Exception):
            publish_sdp_to_knb(
                unchanged,
                public=True,
                dry_run=True,
                revision_manifest=manifest_path,
            )

    def test_revision_source_manifest_must_be_verified(self):
        sdp = _fixture_sdp(self)
        publish_sdp_to_knb(sdp, public=True, dry_run=True)
        manifest_path = os.path.join(sdp, "publication", "knb-manifest.json")
        with self.assertRaises(ValueError) as caught:
            knb._revision_manifest(manifest_path)
        self.assertIn("verified", str(caught.exception))

    def test_revision_source_manifest_must_have_an_intact_fingerprint(self):
        sdp = _fixture_sdp(self)
        manifest_path = self._verified_manifest(sdp)
        with open(manifest_path, encoding="utf-8") as handle:
            manifest = json.load(handle)
        manifest["objects"][0]["sha256"] = "0" * 64
        with open(manifest_path, "w", encoding="utf-8") as handle:
            handle.write(knb._json_bytes(manifest).decode("utf-8"))
        with self.assertRaises(ValueError):
            knb._revision_manifest(manifest_path)

    def test_revision_cannot_change_access(self):
        prior = _r_manifest()
        prior["objects"] = prior["objects"]
        with self.assertRaises(ValueError) as caught:
            knb._revision_context(
                prior, {"public": False, "series_id": prior["series_id"]}
            )
        self.assertIn("public/private access", str(caught.exception))

    def test_revision_cannot_change_series(self):
        prior = _r_manifest()
        with self.assertRaises(ValueError):
            knb._revision_context(
                prior, {"public": True, "series_id": "urn:uuid:other"}
            )

    def test_reusing_prior_pids_is_refused(self):
        revision = {
            "metadata_pid": "urn:uuid:a",
            "resource_map_pid": "urn:uuid:b",
        }
        knb._require_new_revision_pids(revision, "urn:uuid:c", "urn:uuid:d")
        with self.assertRaises(ValueError) as caught:
            knb._require_new_revision_pids(revision, "urn:uuid:a", "urn:uuid:b")
        self.assertIn("revision_key", str(caught.exception))


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
