"""
Offline parity tests for reviewed EML 2.2.0 export (metasalmon 0.1.7 parity).

Fixtures under tests/data/eml/ were generated by running metasalmon at the
v0.1.7 tag (emld 0.5.3, R 4.5.2 — see expected.json["generated_by"]): two
source SDPs, the four EML documents R produced from them, and the identifiers
and object metadata R returned.

Parity here is STRUCTURAL, not byte-level: R serializes through libxml2 and
Python through ElementTree, so the two formatters differ in whitespace while
the documents are identical. `ET.canonicalize(strip_text=True)` is the
comparison, per the S10 execplan's contract-level ruling for formatter
output. The identifiers ARE compared exactly — they are UUIDv5 digests, so
any semantic drift in what feeds them changes the value.

The EML path requires the optional `metasalmonpy[eml]` extra (lxml for XSD
validation, PyYAML for the mapping sidecar), mirroring R's up-front
`requireNamespace("emld")` gate. Every test that exercises the path is
skipped when the extra is absent, so the core suite stays green without it.
"""

import json
import os
import shutil
import unittest
import xml.etree.ElementTree as ET

try:
    import pandas as pd
except ImportError:  # pragma: no cover
    pd = None

if pd is None:
    raise unittest.SkipTest("pandas not installed")

import metasalmonpy.eml as eml_module
from metasalmonpy import write_eml_from_sdp

_DATA_DIR = os.path.join(os.path.dirname(__file__), "data", "eml")


def _extra_available() -> bool:
    try:
        import lxml.etree  # noqa: F401
        import yaml  # noqa: F401
    except ImportError:
        return False
    return True


_REQUIRES_EXTRA = unittest.skipUnless(
    _extra_available(),
    "requires the metasalmonpy[eml] extra (lxml, PyYAML)",
)


def _expected() -> dict:
    with open(os.path.join(_DATA_DIR, "expected.json"), encoding="utf-8") as handle:
        return json.load(handle)


def _canonical(path: str) -> str:
    return ET.canonicalize(from_file=path, strip_text=True)


def _fixture_sdp(test_case: unittest.TestCase, name: str) -> str:
    """Copy a fixture SDP into a temp dir so the export can write into it."""
    import tempfile

    root = tempfile.mkdtemp()
    test_case.addCleanup(shutil.rmtree, root, True)
    target = os.path.join(root, "sdp")
    shutil.copytree(os.path.join(_DATA_DIR, name), target)
    return target


class EmlExtraGateTests(unittest.TestCase):
    """The optional-extra gate mirrors R's requireNamespace('emld')."""

    def test_missing_extra_raises_an_actionable_error(self):
        import builtins

        real_import = builtins.__import__

        def blocked(name, *args, **kwargs):
            if name in ("lxml.etree", "lxml", "yaml"):
                raise ImportError(f"blocked {name}")
            return real_import(name, *args, **kwargs)

        builtins.__import__ = blocked
        try:
            with self.assertRaises(ImportError) as caught:
                eml_module._require_eml_extra()
        finally:
            builtins.__import__ = real_import
        message = str(caught.exception)
        self.assertIn("metasalmonpy[eml]", message)
        self.assertIn("lxml", message)


@_REQUIRES_EXTRA
class EmlStructuralParityTests(unittest.TestCase):
    """Python's document must match R's, structurally and by identifier."""

    def test_default_profile_matches_r(self):
        expected = _expected()["default"]
        sdp = _fixture_sdp(self, "sdp-default")

        result = write_eml_from_sdp(sdp, overwrite=True)

        self.assertEqual(result["package_id"], expected["package_id"])
        self.assertEqual(result["series_id"], expected["series_id"])
        self.assertEqual(result["eml_version"], expected["eml_version"])
        self.assertEqual(result["format_id"], expected["format_id"])
        self.assertEqual(
            _canonical(result["path"]),
            _canonical(os.path.join(_DATA_DIR, "eml-default.xml")),
        )

    def test_skos_profile_matches_r(self):
        # The SKOS compound-variable profile annotates differently; R and
        # Python must still agree on the whole document.
        expected = _expected()["skos"]
        sdp = _fixture_sdp(self, "sdp-skos")

        result = write_eml_from_sdp(sdp, overwrite=True)

        self.assertEqual(result["package_id"], expected["package_id"])
        self.assertEqual(result["series_id"], expected["series_id"])
        self.assertEqual(
            _canonical(result["path"]),
            _canonical(os.path.join(_DATA_DIR, "eml-skos.xml")),
        )

    def test_data_object_metadata_matches_r(self):
        # PIDs are UUIDv5 over the object bytes, so a checksum or size drift
        # would change them; assert the whole block R returned.
        expected = _expected()["default"]["data_objects"]
        sdp = _fixture_sdp(self, "sdp-default")

        result = write_eml_from_sdp(sdp, overwrite=True)

        objects = result["data_objects"]
        self.assertEqual(len(objects), len(expected))
        for actual_row, expected_row in zip(
            objects.to_dict("records") if hasattr(objects, "to_dict") else objects,
            expected,
        ):
            for field, value in expected_row.items():
                self.assertEqual(actual_row[field], value, msg=field)

    def test_export_is_deterministic_across_runs(self):
        first = _fixture_sdp(self, "sdp-default")
        second = _fixture_sdp(self, "sdp-default")

        first_result = write_eml_from_sdp(first, overwrite=True)
        second_result = write_eml_from_sdp(second, overwrite=True)

        with open(first_result["path"], "rb") as handle:
            first_bytes = handle.read()
        with open(second_result["path"], "rb") as handle:
            second_bytes = handle.read()
        self.assertEqual(first_bytes, second_bytes)
        self.assertEqual(first_result["package_id"], second_result["package_id"])

    def test_revision_key_changes_the_package_id_only(self):
        expected = _expected()["revision"]
        sdp = _fixture_sdp(self, "sdp-default")
        mapping_path = os.path.join(sdp, "metadata", "eml-mapping.yml")

        import yaml

        with open(mapping_path, encoding="utf-8") as handle:
            mapping = yaml.safe_load(handle)
        mapping["publication"]["revision_key"] = expected["revision_key"]
        with open(mapping_path, "w", encoding="utf-8") as handle:
            yaml.safe_dump(mapping, handle, sort_keys=False)

        result = write_eml_from_sdp(sdp, overwrite=True)

        # A new revision is a new package identity in the same series.
        self.assertEqual(result["package_id"], expected["package_id"])
        self.assertEqual(result["series_id"], expected["series_id"])
        self.assertEqual(
            _canonical(result["path"]),
            _canonical(os.path.join(_DATA_DIR, "eml-revision.xml")),
        )

    def test_written_document_is_xsd_valid(self):
        # lxml is libxml2, the engine behind emld::eml_validate, so an
        # accept here is the same accept R makes.
        sdp = _fixture_sdp(self, "sdp-default")
        result = write_eml_from_sdp(sdp, overwrite=True)
        self.assertTrue(result["validation"])


@_REQUIRES_EXTRA
class EmlMappingSidecarTests(unittest.TestCase):
    """Sidecar failure modes mirror R's, which refuses to infer."""

    def _mapping(self, sdp: str) -> dict:
        import yaml

        with open(
            os.path.join(sdp, "metadata", "eml-mapping.yml"), encoding="utf-8"
        ) as handle:
            return yaml.safe_load(handle)

    def _write_mapping(self, sdp: str, mapping: dict) -> None:
        import yaml

        with open(
            os.path.join(sdp, "metadata", "eml-mapping.yml"), "w", encoding="utf-8"
        ) as handle:
            yaml.safe_dump(mapping, handle, sort_keys=False)

    def test_missing_sidecar_raises(self):
        sdp = _fixture_sdp(self, "sdp-default")
        os.remove(os.path.join(sdp, "metadata", "eml-mapping.yml"))
        with self.assertRaises(Exception):
            write_eml_from_sdp(sdp, overwrite=True)

    def test_missing_required_field_raises(self):
        sdp = _fixture_sdp(self, "sdp-default")
        mapping = self._mapping(sdp)
        del mapping["contacts"]
        self._write_mapping(sdp, mapping)
        with self.assertRaises(Exception):
            write_eml_from_sdp(sdp, overwrite=True)

    def test_malformed_yaml_raises(self):
        sdp = _fixture_sdp(self, "sdp-default")
        with open(
            os.path.join(sdp, "metadata", "eml-mapping.yml"), "w", encoding="utf-8"
        ) as handle:
            handle.write("version: 1\n  bad indent: [unclosed\n")
        with self.assertRaises(Exception):
            write_eml_from_sdp(sdp, overwrite=True)

    def test_overwrite_is_required_only_for_different_bytes(self):
        # R's contract: re-writing an identical document is allowed; only a
        # document whose bytes differ needs `overwrite`.
        sdp = _fixture_sdp(self, "sdp-default")
        first = write_eml_from_sdp(sdp, overwrite=True)

        # Identical re-write, no overwrite flag: allowed.
        again = write_eml_from_sdp(sdp, overwrite=False)
        self.assertEqual(again["package_id"], first["package_id"])

        # Different bytes at the same path: refused without overwrite.
        with open(first["path"], "a", encoding="utf-8") as handle:
            handle.write("<!-- edited -->\n")
        with self.assertRaises(Exception):
            write_eml_from_sdp(sdp, overwrite=False)
        self.assertTrue(write_eml_from_sdp(sdp, overwrite=True)["validation"])


@_REQUIRES_EXTRA
class EmlIdentifierTests(unittest.TestCase):
    """UUIDv5 derivation must match R's exactly, or every PID drifts."""

    def test_uuid5_matches_r(self):
        # The fixture value is R's .ms_eml_uuid5("demo"); every PID in the
        # document derives from this function, so a namespace or encoding
        # difference would drift every identifier at once.
        expected = _expected()["uuid5_demo"]
        self.assertEqual(eml_module._uuid5("demo"), expected)


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
