"""SSSOM 1.1 support tests (metasalmon 0.1.7 replay, S10 chunk 1).

Byte-parity fixtures under ``tests/data/sssom/`` were generated by running
metasalmon's R implementation (``R/sssom.R``, the spec) directly:

- ``src/``            source mapping sets (unsorted curie maps, scrambled
                       column order, unsorted rows, non-ASCII text)
- ``canonical/``      R's ``.ms_sssom_canonical_bytes`` output for each source
- ``r-sdp/``          an SDP written by R's ``write_sdp_sssom`` over all three
- ``checksums.json``  sha256 of every fixture, computed in R

THE parity contract: the Python canonical-bytes builder must reproduce R's
bytes exactly — same mapping set, same sha256. The failure-mode tests mirror
metasalmon's ``tests/testthat/test-sssom.R``.
"""

import hashlib
import json
import unittest
from pathlib import Path

import pytest

try:
    import pandas as pd
except ImportError:  # pragma: no cover
    pd = None

if pd is None:
    raise unittest.SkipTest("pandas not installed")

import metasalmonpy
from metasalmonpy import sssom
from metasalmonpy.sssom import (
    SssomMappingSet,
    read_sssom_mapping_set,
    validate_sdp_sssom,
    write_sdp_sssom,
)

DATA = Path(__file__).parent / "data" / "sssom"
CHECKSUMS = json.loads((DATA / "checksums.json").read_text(encoding="utf-8"))
FIXTURES = ("psc-to-gcdfo.sssom.tsv", "multi-sort.sssom.tsv", "gaps.sssom.tsv")


def sssom_text(
    mapping_set_id="https://example.org/mappings/psc-to-gcdfo",
    mapping_set_version="2026-07-31",
    object_source="https://w3id.org/gcdfo/salmon",
    object_source_version="0.0.8",
    rows=None,
    extra_prefixes=(),
    extra_metadata=(),
):
    """Mirror of the R test helper ``sssom_test_text``."""
    if rows is None:
        rows = [
            "\t".join(
                (
                    "psc:PSC-CV-000001",
                    "Net",
                    "skos:exactMatch",
                    "gcdfo:FixedSiteCensusManual",
                    "Fixed Site Census (Manual)",
                    "semapv:ManualMappingCuration",
                )
            )
        ]
    prefixes = [
        "#   psc: https://w3id.org/psc/vocab/concept/",
        "#   gcdfo: https://w3id.org/gcdfo/salmon#",
        "#   skos: http://www.w3.org/2004/02/skos/core#",
        "#   semapv: https://w3id.org/semapv/vocab/",
        "#   sssom: https://w3id.org/sssom/",
        *extra_prefixes,
    ]
    lines = [
        "# sssom_version: 1.1",
        f"# mapping_set_id: {mapping_set_id}",
        f"# mapping_set_version: {mapping_set_version}",
        "# license: https://creativecommons.org/licenses/by/4.0/",
        "# subject_source: https://w3id.org/psc/vocab/",
        "# subject_source_version: v0.2.0",
        f"# object_source: {object_source}",
        f"# object_source_version: {object_source_version}",
        *extra_metadata,
        "# curie_map:",
        *prefixes,
        "\t".join(
            (
                "subject_id",
                "subject_label",
                "predicate_id",
                "object_id",
                "object_label",
                "mapping_justification",
            )
        ),
        *rows,
    ]
    return "\n".join(lines) + "\n"


def write_raw(path, text):
    Path(path).write_bytes(text.encode("utf-8"))
    return Path(path)


# --- byte parity against the R implementation --------------------------------


@pytest.mark.parametrize("name", FIXTURES)
def test_canonical_bytes_match_r_exactly(name):
    mapping_set = read_sssom_mapping_set(DATA / "src" / name)
    got = sssom._canonical_bytes(mapping_set)
    assert hashlib.sha256(got).hexdigest() == CHECKSUMS["canonical"][name]
    assert got == (DATA / "canonical" / name).read_bytes()


@pytest.mark.parametrize("name", FIXTURES)
def test_canonical_bytes_are_idempotent(name):
    canonical_path = DATA / "canonical" / name
    reread = read_sssom_mapping_set(canonical_path)
    assert sssom._canonical_bytes(reread) == canonical_path.read_bytes()


def test_reader_accepts_r_fixture_and_parses_metadata():
    result = read_sssom_mapping_set(DATA / "src" / "psc-to-gcdfo.sssom.tsv")
    assert isinstance(result, SssomMappingSet)
    assert result.metadata["sssom_version"] == "1.1"
    assert (
        result.metadata["curie_map"]["psc"]
        == "https://w3id.org/psc/vocab/concept/"
    )
    assert list(result.metadata["curie_map"]) == sorted(
        result.metadata["curie_map"]
    )
    assert len(result.mappings) == 1
    assert result.mappings["predicate_id"].tolist() == ["skos:exactMatch"]
    assert validate_sdp_sssom(DATA / "src" / "psc-to-gcdfo.sssom.tsv") is True


def test_unsorted_input_normalizes_to_sorted_canonical_output():
    mapping_set = read_sssom_mapping_set(DATA / "src" / "multi-sort.sssom.tsv")
    text = sssom._canonical_bytes(mapping_set).decode("utf-8")
    lines = text.split("\n")
    curie_lines = [line for line in lines if line.startswith("#   ")]
    assert [line.split(":")[0].strip("# ") for line in curie_lines] == [
        "SDO",
        "gcdfo",
        "psc",
        "semapv",
        "skos",
        "sssom",
    ]
    header = next(line for line in lines if line.startswith("subject_id"))
    # Scrambled source columns come back in the canonical column order.
    assert header.split("\t") == [
        "subject_id",
        "subject_label",
        "predicate_id",
        "object_id",
        "object_label",
        "mapping_justification",
        "mapping_cardinality",
        "confidence",
        "comment",
    ]
    data_rows = lines[lines.index(header) + 1 : -1]
    keys = [tuple(row.split("\t")) for row in data_rows]
    assert keys == sorted(keys)
    # Tie on subject_id resolved by the next canonical column that differs.
    assert data_rows[0].split("\t")[2] == "skos:broadMatch"
    assert data_rows[1].split("\t")[2] == "skos:exactMatch"


def test_python_validates_r_written_sdp():
    assert validate_sdp_sssom(DATA / "r-sdp") is True


def test_python_writer_reproduces_r_sdp_mapping_set_bytes(tmp_path):
    sdp = tmp_path / "sdp"
    sdp.mkdir()
    manifest_path = write_sdp_sssom(
        sdp, mapping_sets=[DATA / "src" / name for name in FIXTURES]
    )
    assert manifest_path == str(sdp / "metadata" / "semantic" / "mapping-sets.json")

    for name in FIXTURES:
        written = (sdp / "metadata" / "semantic" / name).read_bytes()
        assert (
            hashlib.sha256(written).hexdigest()
            == CHECKSUMS["r_sdp_semantic"][name]
        )
        assert written == (
            DATA / "r-sdp" / "metadata" / "semantic" / name
        ).read_bytes()

    # Manifest parity is contract-level: identical mapping-set entries (paths,
    # hashes, row counts, metadata), honest per-implementation provenance.
    ours = json.loads(Path(manifest_path).read_text(encoding="utf-8"))
    theirs = json.loads(
        (DATA / "r-sdp" / "metadata" / "semantic" / "mapping-sets.json").read_text(
            encoding="utf-8"
        )
    )
    assert ours["schema_version"] == theirs["schema_version"] == "1.0"
    assert ours["sssom_version"] == theirs["sssom_version"] == "1.1"
    assert ours["mapping_sets"] == theirs["mapping_sets"]
    assert ours["provenance"]["generated_by"] == "metasalmonpy.write_sdp_sssom"
    assert theirs["provenance"]["generated_by"] == "metasalmon::write_sdp_sssom"


def test_writer_is_deterministic_across_input_order(tmp_path):
    first, second = tmp_path / "first", tmp_path / "second"
    first.mkdir()
    second.mkdir()
    paths = [DATA / "src" / name for name in FIXTURES]
    write_sdp_sssom(first, mapping_sets=paths)
    write_sdp_sssom(second, mapping_sets=list(reversed(paths)))
    first_files = sorted(p.name for p in (first / "metadata" / "semantic").iterdir())
    second_files = sorted(p.name for p in (second / "metadata" / "semantic").iterdir())
    assert first_files == second_files
    for name in first_files:
        assert (first / "metadata" / "semantic" / name).read_bytes() == (
            second / "metadata" / "semantic" / name
        ).read_bytes()
    manifest = json.loads(
        (first / "metadata" / "semantic" / "mapping-sets.json").read_text(
            encoding="utf-8"
        )
    )
    # Asserting `ids == sorted(ids)` would only prove Python agrees with
    # Python. The expectation is the order R wrote into the fixture SDP.
    r_manifest = json.loads(
        (DATA / "r-sdp" / "metadata" / "semantic" / "mapping-sets.json").read_text(
            encoding="utf-8"
        )
    )
    expected_ids = [entry["mapping_set_id"] for entry in r_manifest["mapping_sets"]]
    assert expected_ids == [
        "https://example.org/mappings/multi-sort",
        "https://example.org/mappings/psc-to-gcdfo",
        "https://example.org/mappings/psc-to-sdo-gaps",
    ]
    assert [
        entry["mapping_set_id"] for entry in manifest["mapping_sets"]
    ] == expected_ids


# --- gap (sssom:NoTermFound) semantics ----------------------------------------


def test_explicit_one_to_zero_no_match_record_is_supported():
    result = read_sssom_mapping_set(DATA / "src" / "gaps.sssom.tsv")
    gap = result.mappings[result.mappings["object_id"] == "sssom:NoTermFound"]
    assert len(gap) == 1
    assert gap["mapping_cardinality"].tolist() == ["1:0"]


def test_gap_record_requires_matching_cardinality(tmp_path):
    text = (DATA / "src" / "gaps.sssom.tsv").read_text(encoding="utf-8")
    path = write_raw(tmp_path / "bad-gap.sssom.tsv", text.replace("\t1:0", "\t1:1"))
    with pytest.raises(ValueError, match="mapping_cardinality"):
        read_sssom_mapping_set(path)


def test_zero_cardinality_requires_no_term_found(tmp_path):
    rows = [
        "\t".join(
            (
                "psc:PSC-CV-000001",
                "Net",
                "skos:exactMatch",
                "gcdfo:FixedSiteCensusManual",
                "Fixed Site Census (Manual)",
                "semapv:ManualMappingCuration",
                "1:0",
            )
        )
    ]
    text = sssom_text(rows=rows).replace(
        "mapping_justification\n", "mapping_justification\tmapping_cardinality\n"
    )
    path = write_raw(tmp_path / "zero.sssom.tsv", text)
    with pytest.raises(ValueError, match="NoTermFound"):
        read_sssom_mapping_set(path)


def test_no_term_found_is_only_valid_in_subject_or_object(tmp_path):
    text = sssom_text().replace("skos:exactMatch", "sssom:NoTermFound")
    path = write_raw(tmp_path / "misplaced.sssom.tsv", text)
    with pytest.raises(ValueError, match="subject_id or object_id"):
        read_sssom_mapping_set(path)


def test_gap_cannot_contradict_a_positive_mapping(tmp_path):
    positive = "\t".join(
        (
            "psc:PSC-CV-000001",
            "Net",
            "skos:exactMatch",
            "gcdfo:FixedSiteCensusManual",
            "Fixed Site Census (Manual)",
            "semapv:ManualMappingCuration",
            "1:1",
        )
    )
    gap = "\t".join(
        (
            "psc:PSC-CV-000001",
            "Net",
            "skos:relatedMatch",
            "sssom:NoTermFound",
            "",
            "semapv:ManualMappingCuration",
            "1:0",
        )
    )
    text = sssom_text(rows=[positive, gap]).replace(
        "mapping_justification\n", "mapping_justification\tmapping_cardinality\n"
    )
    path = write_raw(tmp_path / "contradiction.sssom.tsv", text)
    with pytest.raises(ValueError, match="contradict"):
        read_sssom_mapping_set(path)


def test_gap_requires_effective_object_source_version(tmp_path):
    text = sssom_text().replace("# object_source_version: 0.0.8\n", "")
    path = write_raw(tmp_path / "missing-version.sssom.tsv", text)
    with pytest.raises(ValueError, match="object_source_version"):
        read_sssom_mapping_set(path)


def test_row_level_object_source_override_clears_inherited_version(tmp_path):
    # A gap row overriding object_source needs its own version: the set-level
    # version cannot describe a different vocabulary release.
    row = "\t".join(
        (
            "psc:PSC-CV-000001",
            "Net",
            "skos:relatedMatch",
            "sssom:NoTermFound",
            "",
            "semapv:ManualMappingCuration",
            "1:0",
            "https://w3id.org/other/vocab",
        )
    )
    text = sssom_text(rows=[row]).replace(
        "mapping_justification\n",
        "mapping_justification\tmapping_cardinality\tobject_source\n",
    )
    path = write_raw(tmp_path / "override.sssom.tsv", text)
    with pytest.raises(ValueError, match="object_source_version"):
        read_sssom_mapping_set(path)


# --- byte and delimiter formats ------------------------------------------------


def test_rejects_utf8_bom(tmp_path):
    path = tmp_path / "bom.sssom.tsv"
    path.write_bytes(b"\xef\xbb\xbf" + sssom_text().encode("utf-8"))
    with pytest.raises(ValueError, match="BOM"):
        read_sssom_mapping_set(path)


def test_rejects_crlf_line_endings(tmp_path):
    path = write_raw(tmp_path / "crlf.sssom.tsv", sssom_text().replace("\n", "\r\n"))
    with pytest.raises(ValueError, match="carriage"):
        read_sssom_mapping_set(path)


def test_rejects_non_tab_delimiters(tmp_path):
    path = write_raw(tmp_path / "comma.sssom.tsv", sssom_text().replace("\t", ","))
    with pytest.raises(ValueError, match="tab-delimited"):
        read_sssom_mapping_set(path)


def test_rejects_missing_trailing_newline(tmp_path):
    path = write_raw(tmp_path / "no-newline.sssom.tsv", sssom_text().rstrip("\n"))
    with pytest.raises(ValueError, match="LF newline"):
        read_sssom_mapping_set(path)


def test_rejects_empty_file_and_nul_bytes(tmp_path):
    empty = tmp_path / "empty.sssom.tsv"
    empty.write_bytes(b"")
    with pytest.raises(ValueError, match="empty"):
        read_sssom_mapping_set(empty)

    nul = tmp_path / "nul.sssom.tsv"
    nul.write_bytes(sssom_text().encode("utf-8") + b"\x00\n")
    with pytest.raises(ValueError, match="NUL"):
        read_sssom_mapping_set(nul)


def test_rejects_invalid_utf8(tmp_path):
    path = tmp_path / "latin1.sssom.tsv"
    path.write_bytes(sssom_text().encode("utf-8").replace(b"Net", b"N\xe9t"))
    with pytest.raises(ValueError, match="UTF-8"):
        read_sssom_mapping_set(path)


def test_missing_file_raises_actionable_error(tmp_path):
    with pytest.raises(FileNotFoundError, match="does not exist"):
        read_sssom_mapping_set(tmp_path / "absent.sssom.tsv")


# --- header and metadata validation --------------------------------------------


def test_file_must_begin_with_metadata_comments(tmp_path):
    text = sssom_text()
    body = "\n".join(
        line for line in text.split("\n") if not line.startswith("#")
    )
    path = write_raw(tmp_path / "no-metadata.sssom.tsv", body)
    with pytest.raises(ValueError, match="YAML metadata"):
        read_sssom_mapping_set(path)


def test_rejects_missing_required_metadata(tmp_path):
    text = sssom_text().replace("# license: https://creativecommons.org/licenses/by/4.0/\n", "")
    path = write_raw(tmp_path / "no-license.sssom.tsv", text)
    with pytest.raises(ValueError, match="missing required fields: license"):
        read_sssom_mapping_set(path)


def test_rejects_unsupported_metadata_fields(tmp_path):
    text = sssom_text(extra_metadata=["# component_registry: https://example.org/x"])
    path = write_raw(tmp_path / "unknown-meta.sssom.tsv", text)
    with pytest.raises(ValueError, match="unsupported SSSOM fields: component_registry"):
        read_sssom_mapping_set(path)


def test_rejects_wrong_sssom_version(tmp_path):
    text = sssom_text().replace("# sssom_version: 1.1", "# sssom_version: 1.0")
    path = write_raw(tmp_path / "wrong-version.sssom.tsv", text)
    with pytest.raises(ValueError, match="sssom_version: 1.1"):
        read_sssom_mapping_set(path)


def test_rejects_relative_mapping_set_id(tmp_path):
    text = sssom_text(mapping_set_id="mappings/psc-to-gcdfo")
    path = write_raw(tmp_path / "relative-id.sssom.tsv", text)
    with pytest.raises(ValueError, match="mapping_set_id.*absolute URI"):
        read_sssom_mapping_set(path)


def test_rejects_duplicate_curie_prefixes(tmp_path):
    text = sssom_text(extra_prefixes=["#   psc: https://example.org/duplicate/"])
    path = write_raw(tmp_path / "dup-prefix.sssom.tsv", text)
    with pytest.raises(ValueError, match="not valid YAML"):
        read_sssom_mapping_set(path)


def test_rejects_invalid_curie_prefix_name(tmp_path):
    text = sssom_text(extra_prefixes=["#   9bad: https://example.org/bad/"])
    path = write_raw(tmp_path / "bad-prefix.sssom.tsv", text)
    with pytest.raises(ValueError, match="invalid prefix name"):
        read_sssom_mapping_set(path)


def test_rejects_non_absolute_curie_expansion(tmp_path):
    text = sssom_text(extra_prefixes=["#   rel: not a uri"])
    path = write_raw(tmp_path / "bad-expansion.sssom.tsv", text)
    with pytest.raises(ValueError, match="curie_map expansion must be an absolute URI"):
        read_sssom_mapping_set(path)


def test_rejects_literal_metadata_types(tmp_path):
    text = sssom_text(extra_metadata=["# object_type: rdfs literal"])
    path = write_raw(tmp_path / "literal-meta.sssom.tsv", text)
    with pytest.raises(ValueError, match="literal"):
        read_sssom_mapping_set(path)


def test_yaml_subset_quoting_and_comments_match_r(tmp_path):
    # Both behaviours verified against R's reader: single-quoted scalars are
    # accepted, and a whitespace-preceded '#' ends a plain scalar while a
    # glued '#' (IRI fragment) does not.
    quoted = sssom_text().replace(
        "# mapping_set_version: 2026-07-31",
        "# mapping_set_version: '2026-07-31'",
    )
    path = write_raw(tmp_path / "quoted.sssom.tsv", quoted)
    assert (
        read_sssom_mapping_set(path).metadata["mapping_set_version"]
        == "2026-07-31"
    )

    commented = sssom_text().replace(
        "# mapping_set_version: 2026-07-31",
        "# mapping_set_version: 2026-07-31 # reviewed",
    )
    path = write_raw(tmp_path / "commented.sssom.tsv", commented)
    result = read_sssom_mapping_set(path)
    assert result.metadata["mapping_set_version"] == "2026-07-31"
    assert result.metadata["curie_map"]["gcdfo"] == "https://w3id.org/gcdfo/salmon#"


# --- table structure and profile validation ------------------------------------


def test_rejects_unknown_prefixes_in_rows(tmp_path):
    text = sssom_text().replace("gcdfo:FixedSiteCensusManual", "mystery:Term")
    path = write_raw(tmp_path / "unknown-prefix.sssom.tsv", text)
    with pytest.raises(ValueError, match="unknown CURIE prefix 'mystery'"):
        read_sssom_mapping_set(path)


def test_rejects_missing_required_columns(tmp_path):
    text = sssom_text()
    text = text.replace("\tmapping_justification", "")
    text = text.replace("\tsemapv:ManualMappingCuration", "")
    path = write_raw(tmp_path / "missing-column.sssom.tsv", text)
    with pytest.raises(ValueError, match="mapping_justification"):
        read_sssom_mapping_set(path)


def test_rejects_decomposition_columns(tmp_path):
    text = sssom_text()
    text = text.replace(
        "mapping_justification\n", "mapping_justification\tcomponent_id\n"
    )
    text = text.replace(
        "semapv:ManualMappingCuration\n",
        "semapv:ManualMappingCuration\tsmn:SpawnerStageContext\n",
    )
    path = write_raw(tmp_path / "decomposition.sssom.tsv", text)
    with pytest.raises(ValueError, match="component_id"):
        read_sssom_mapping_set(path)


def test_rejects_literal_assignments_in_rows(tmp_path):
    text = sssom_text(
        extra_prefixes=["#   rdfs: http://www.w3.org/2000/01/rdf-schema#"]
    )
    text = text.replace(
        "mapping_justification\n", "mapping_justification\tobject_type\n"
    )
    text = text.replace(
        "semapv:ManualMappingCuration\n",
        "semapv:ManualMappingCuration\trdfs literal\n",
    )
    path = write_raw(tmp_path / "literal.sssom.tsv", text)
    with pytest.raises(ValueError, match="literal"):
        read_sssom_mapping_set(path)


def test_rejects_invalid_justification(tmp_path):
    text = sssom_text().replace(
        "semapv:ManualMappingCuration", "semapv:VibesBasedMatching"
    )
    path = write_raw(tmp_path / "bad-justification.sssom.tsv", text)
    with pytest.raises(ValueError, match="SEMAPV"):
        read_sssom_mapping_set(path)


def test_rejects_blank_rows_and_comments_after_header(tmp_path):
    # An interior blank line is a blank row.
    interior = write_raw(
        tmp_path / "interior.sssom.tsv",
        sssom_text().replace("mapping_justification\n", "mapping_justification\n\n"),
    )
    with pytest.raises(ValueError, match="blank row"):
        read_sssom_mapping_set(interior)

    # Two extra trailing newlines leave a blank row behind...
    double = write_raw(tmp_path / "double.sssom.tsv", sssom_text() + "\n\n")
    with pytest.raises(ValueError, match="blank row"):
        read_sssom_mapping_set(double)

    # ...but exactly one is tolerated, mirroring R's strsplit() rule of
    # omitting a single trailing empty field.
    single = write_raw(tmp_path / "single.sssom.tsv", sssom_text() + "\n")
    assert len(read_sssom_mapping_set(single).mappings) == 1

    commented = write_raw(
        tmp_path / "comment.sssom.tsv", sssom_text() + "# stray comment\n"
    )
    with pytest.raises(ValueError, match="before the TSV header"):
        read_sssom_mapping_set(commented)


def test_rejects_ragged_rows(tmp_path):
    path = write_raw(
        tmp_path / "ragged.sssom.tsv",
        sssom_text().replace("\tFixed Site Census (Manual)", ""),
    )
    with pytest.raises(ValueError, match="tab delimiters"):
        read_sssom_mapping_set(path)


def test_rejects_duplicate_mappings(tmp_path):
    row = "\t".join(
        (
            "psc:PSC-CV-000001",
            "Net",
            "skos:exactMatch",
            "gcdfo:FixedSiteCensusManual",
            "Fixed Site Census (Manual)",
            "semapv:ManualMappingCuration",
        )
    )
    path = write_raw(tmp_path / "dup.sssom.tsv", sssom_text(rows=[row, row]))
    with pytest.raises(ValueError, match="duplicate subject/predicate/object"):
        read_sssom_mapping_set(path)


def test_rejects_blank_required_values(tmp_path):
    text = sssom_text().replace("skos:exactMatch", "")
    path = write_raw(tmp_path / "blank-required.sssom.tsv", text)
    with pytest.raises(ValueError, match="predicate_id contains a blank value"):
        read_sssom_mapping_set(path)


def test_rejects_invalid_cardinality_value(tmp_path):
    row = "\t".join(
        (
            "psc:PSC-CV-000001",
            "Net",
            "skos:exactMatch",
            "gcdfo:FixedSiteCensusManual",
            "Fixed Site Census (Manual)",
            "semapv:ManualMappingCuration",
            "2:2",
        )
    )
    text = sssom_text(rows=[row]).replace(
        "mapping_justification\n", "mapping_justification\tmapping_cardinality\n"
    )
    path = write_raw(tmp_path / "bad-cardinality.sssom.tsv", text)
    with pytest.raises(ValueError, match="mapping_cardinality contains an invalid value"):
        read_sssom_mapping_set(path)


# --- write_sdp_sssom ------------------------------------------------------------


def test_write_is_explicit_and_none_is_a_noop(tmp_path):
    assert write_sdp_sssom(tmp_path, mapping_sets=None) is None
    assert not (tmp_path / "metadata" / "semantic").exists()


def test_write_requires_existing_directory(tmp_path):
    source = write_raw(tmp_path / "approved.sssom.tsv", sssom_text())
    with pytest.raises(ValueError, match="existing SDP directory"):
        write_sdp_sssom(tmp_path / "missing", mapping_sets=source)


def test_write_is_overwrite_safe(tmp_path):
    sdp = tmp_path / "sdp"
    sdp.mkdir()
    source = write_raw(tmp_path / "approved.sssom.tsv", sssom_text())

    manifest_path = write_sdp_sssom(sdp, mapping_sets=source)
    before = Path(manifest_path).read_bytes()
    with pytest.raises(FileExistsError, match="already exists"):
        write_sdp_sssom(sdp, mapping_sets=source)
    assert write_sdp_sssom(sdp, mapping_sets=source, overwrite=True) == manifest_path
    assert Path(manifest_path).read_bytes() == before


def test_write_rejects_duplicate_mapping_set_ids(tmp_path):
    sdp = tmp_path / "sdp"
    sdp.mkdir()
    first = write_raw(tmp_path / "one.sssom.tsv", sssom_text())
    second = write_raw(tmp_path / "two.sssom.tsv", sssom_text())
    with pytest.raises(ValueError, match="duplicate mapping_set_id"):
        write_sdp_sssom(sdp, mapping_sets=[first, second])


def test_write_accepts_in_memory_sets_and_derives_safe_filenames(tmp_path):
    parsed = read_sssom_mapping_set(DATA / "src" / "multi-sort.sssom.tsv")
    sdp = tmp_path / "sdp"
    sdp.mkdir()
    manifest_path = write_sdp_sssom(
        sdp,
        mapping_sets={"metadata": parsed.metadata, "mappings": parsed.mappings},
    )
    # No source path: the filename is derived from mapping_set_id.
    written = sdp / "metadata" / "semantic" / "multi-sort.sssom.tsv"
    assert written.exists()
    assert (
        hashlib.sha256(written.read_bytes()).hexdigest()
        == CHECKSUMS["canonical"]["multi-sort.sssom.tsv"]
    )
    assert validate_sdp_sssom(sdp) is True
    assert manifest_path == str(sdp / "metadata" / "semantic" / "mapping-sets.json")


def test_write_refuses_to_overwrite_symlinks(tmp_path):
    sdp = tmp_path / "sdp"
    (sdp / "metadata" / "semantic").mkdir(parents=True)
    source = write_raw(tmp_path / "approved.sssom.tsv", sssom_text())
    outside = write_raw(tmp_path / "outside.sssom.tsv", sssom_text())
    link = sdp / "metadata" / "semantic" / "approved.sssom.tsv"
    link.symlink_to(outside)
    with pytest.raises(ValueError, match="symlink"):
        write_sdp_sssom(sdp, mapping_sets=source, overwrite=True)


# --- validate_sdp_sssom ----------------------------------------------------------


def _tamper_manifest(sdp, mutate):
    manifest_path = Path(sdp) / "metadata" / "semantic" / "mapping-sets.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    mutate(manifest)
    manifest_path.write_bytes(
        (json.dumps(manifest, indent=2, ensure_ascii=False) + "\n").encode("utf-8")
    )


@pytest.fixture()
def written_sdp(tmp_path):
    sdp = tmp_path / "sdp"
    sdp.mkdir()
    source = write_raw(tmp_path / "approved.sssom.tsv", sssom_text())
    write_sdp_sssom(sdp, mapping_sets=source)
    return sdp


def test_validate_detects_unsafe_manifest_paths(written_sdp):
    def mutate(manifest):
        manifest["mapping_sets"][0]["path"] = (
            "metadata/semantic/../outside.sssom.tsv"
        )

    _tamper_manifest(written_sdp, mutate)
    with pytest.raises(ValueError, match="safe relative"):
        validate_sdp_sssom(written_sdp)


def test_validate_detects_sha256_drift(written_sdp):
    def mutate(manifest):
        manifest["mapping_sets"][0]["sha256"] = "0" * 64

    _tamper_manifest(written_sdp, mutate)
    with pytest.raises(ValueError, match="SHA-256"):
        validate_sdp_sssom(written_sdp)


def test_validate_detects_row_count_drift(written_sdp):
    def mutate(manifest):
        manifest["mapping_sets"][0]["row_count"] = 7

    _tamper_manifest(written_sdp, mutate)
    with pytest.raises(ValueError, match="row count"):
        validate_sdp_sssom(written_sdp)


def test_validate_detects_metadata_drift(written_sdp):
    def mutate(manifest):
        manifest["mapping_sets"][0]["mapping_set_version"] = "9999-01-01"

    _tamper_manifest(written_sdp, mutate)
    with pytest.raises(ValueError, match="mapping_set_version"):
        validate_sdp_sssom(written_sdp)


def test_validate_rejects_unknown_provenance(written_sdp):
    def mutate(manifest):
        manifest["provenance"]["generated_by"] = "somebody-else"

    _tamper_manifest(written_sdp, mutate)
    with pytest.raises(ValueError, match="provenance"):
        validate_sdp_sssom(written_sdp)


def test_validate_requires_manifest(tmp_path):
    sdp = tmp_path / "sdp"
    sdp.mkdir()
    with pytest.raises(FileNotFoundError, match="SSSOM manifest"):
        validate_sdp_sssom(sdp)


def test_validate_detects_missing_referenced_file(written_sdp):
    (written_sdp / "metadata" / "semantic" / "approved.sssom.tsv").unlink()
    with pytest.raises(FileNotFoundError, match="missing file"):
        validate_sdp_sssom(written_sdp)


# --- multi-valued reference columns ------------------------------------------------


def with_author_id(value, **kwargs):
    """``sssom_text`` plus a multi-valued ``author_id`` column on every row."""
    lines = sssom_text(**kwargs).rstrip("\n").split("\n")
    header = next(i for i, line in enumerate(lines) if not line.startswith("#"))
    lines[header] += "\tauthor_id"
    for index in range(header + 1, len(lines)):
        lines[index] += "\t" + value
    return "\n".join(lines) + "\n"


def test_a_single_trailing_pipe_is_accepted_the_way_r_accepts_it(tmp_path):
    # base::strsplit() drops exactly one trailing empty field, so metasalmon
    # v0.1.7 reads "psc:PSC-CV-000900|" as one well-formed reference -- and
    # then writes an SDP this validator used to refuse to read back.
    path = write_raw(
        tmp_path / "trailing.sssom.tsv", with_author_id("psc:PSC-CV-000900|")
    )
    result = read_sssom_mapping_set(path)
    assert result.mappings["author_id"].tolist() == ["psc:PSC-CV-000900|"]


@pytest.mark.parametrize(
    "value",
    [
        "|psc:PSC-CV-000900",
        "psc:PSC-CV-000900||psc:PSC-CV-000901",
        "psc:PSC-CV-000900||",
    ],
)
def test_leading_and_interior_empty_pieces_are_still_refused(tmp_path, value):
    # Only ONE trailing empty is dropped; every other empty piece survives
    # strsplit() and is rejected by R, so it must be rejected here too.
    path = write_raw(tmp_path / "bad.sssom.tsv", with_author_id(value))
    with pytest.raises(ValueError, match="author_id"):
        read_sssom_mapping_set(path)


def test_split_helper_matches_base_strsplit():
    # The exact vectors base::strsplit(x, "|", fixed = TRUE)[[1]] returns.
    assert sssom._split_multivalued("") == []
    assert sssom._split_multivalued("a|") == ["a"]
    assert sssom._split_multivalued("a||") == ["a", ""]
    assert sssom._split_multivalued("|") == [""]
    assert sssom._split_multivalued("|a") == ["", "a"]
    assert sssom._split_multivalued("a||b") == ["a", "", "b"]


# --- written artifacts are ordinary files ------------------------------------------


def test_written_artifacts_use_the_umask_default_mode(tmp_path):
    # R's writeBin + file.rename leaves the umask default (0644 typically);
    # tempfile.mkstemp hard-codes 0600 and os.replace preserves it, so every
    # mapping set this package published was private to its owner.
    sdp = tmp_path / "sdp"
    sdp.mkdir()
    manifest_path = write_sdp_sssom(
        sdp, mapping_sets=[DATA / "src" / name for name in FIXTURES]
    )
    semantic = Path(manifest_path).parent

    reference = semantic / "reference.txt"
    reference.write_text("x", encoding="utf-8")
    expected = reference.stat().st_mode & 0o777

    written = sorted(p for p in semantic.iterdir() if p != reference)
    assert written  # guard against an empty glob silently passing
    for path in written:
        assert path.stat().st_mode & 0o777 == expected, path.name


# --- public API -------------------------------------------------------------------


def test_sssom_entry_points_are_public():
    expected = {"read_sssom_mapping_set", "write_sdp_sssom", "validate_sdp_sssom"}
    assert expected <= set(metasalmonpy.__all__)
    assert all(callable(getattr(metasalmonpy, name)) for name in expected)
