"""Measurement-decomposition tests (sdp-0.3.0 shape, S10 chunk A).

Byte-parity fixtures under ``tests/data/decompositions/`` were generated by
running metasalmon's R implementation (``R/measurement-decompositions.R``)
from **main at e02111a** — the v0.3.0 release tree plus the post-0.3.0 fixes
— over the same ``src/`` rows this suite feeds the Python writer:

- ``era-sdp/``        an SDP whose artifact is metasalmon's own six-component
                      test table, including a ``statistical_modifier``-role
                      gap row (the slot that replaced the transitional
                      ``method`` role at 0.3.0)
- ``full-sdp/``       multi-measurement SDP exercising row sorting across
                      binding keys (C collation: ``Zsite`` before
                      ``counts``), semicolon multi-constraints, a
                      ``value_of_dimension`` relation, a matched
                      ``statistical_modifier`` component enforced by a
                      dictionary ``statistical_modifier_iri``, gap rows, and
                      CSV quoting (comma/quote/semicolon/unicode)
- ``src/``            the scrambled input rows fed to R's writer
- ``checksums.json``  sha256 of every artifact, computed in R

THE parity contract: the Python CSV-bytes builder must reproduce R's
``readr::format_csv`` output exactly — same rows, same bytes, same sha256.
The failure-mode tests mirror metasalmon's era
``tests/testthat/test-measurement-decompositions.R``.
"""

import hashlib
import json
import shutil
import unittest
from pathlib import Path

import pytest

try:
    import pandas as pd
except ImportError:  # pragma: no cover
    pd = None

if pd is None:
    raise unittest.SkipTest("pandas not installed")

import metasalmonpy
from metasalmonpy import measurement_decompositions as decompositions
from metasalmonpy.measurement_decompositions import (
    read_sdp_measurement_decompositions,
    validate_sdp_measurement_decompositions,
    write_sdp_measurement_decompositions,
)

DATA = Path(__file__).parent / "data" / "decompositions"
CHECKSUMS = json.loads((DATA / "checksums.json").read_text(encoding="utf-8"))
FIXTURES = ("era-sdp", "full-sdp")
SRC = {"era-sdp": "era-rows.csv", "full-sdp": "full-rows.csv"}
CSV_REL = Path("metadata") / "semantic" / "measurement-decompositions.csv"
MANIFEST_REL = Path("metadata") / "semantic" / "measurement-decompositions.json"

ERA_CONCEPT = "https://w3id.org/psc/vocab/PSC-CV-000035"


def load_rows(fixture):
    """The scrambled input rows R's writer was fed, as an all-string frame."""
    return pd.read_csv(
        DATA / "src" / SRC[fixture], dtype=str, keep_default_na=False
    )


def era_rows():
    """The era test table in component order (rows 0-5 = orders 1-6)."""
    rows = load_rows("era-sdp")
    rows = rows.sort_values("component_order", key=lambda s: s.astype(int))
    return rows.reset_index(drop=True)


def relation_rows():
    """The full-sdp rows, index-stable for relation mutations."""
    return load_rows("full-sdp").reset_index(drop=True)


def make_sdp(tmp_path, fixture, name="sdp"):
    """A fresh SDP with the fixture's dictionary and no semantic artifacts."""
    sdp = tmp_path / name
    (sdp / "metadata").mkdir(parents=True)
    shutil.copy(
        DATA / fixture / "metadata" / "column_dictionary.csv",
        sdp / "metadata" / "column_dictionary.csv",
    )
    return sdp


def rehash(root):
    """Recompute the manifest's sha256 after tampering with the CSV."""
    manifest_path = root / MANIFEST_REL
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["artifact"]["sha256"] = hashlib.sha256(
        (root / CSV_REL).read_bytes()
    ).hexdigest()
    manifest_path.write_bytes(
        (json.dumps(manifest, indent=2, ensure_ascii=False) + "\n").encode(
            "utf-8"
        )
    )


def tamper_manifest(root, mutate):
    manifest_path = root / MANIFEST_REL
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    mutate(manifest)
    manifest_path.write_bytes(
        (json.dumps(manifest, indent=2, ensure_ascii=False) + "\n").encode(
            "utf-8"
        )
    )


@pytest.fixture()
def written_sdp(tmp_path):
    sdp = make_sdp(tmp_path, "era-sdp")
    write_sdp_measurement_decompositions(sdp, era_rows())
    return sdp


# --- byte parity against the R implementation ---------------------------------


@pytest.mark.parametrize("fixture", FIXTURES)
def test_python_writer_reproduces_r_bytes_exactly(tmp_path, fixture):
    sdp = make_sdp(tmp_path, fixture)
    manifest_path = write_sdp_measurement_decompositions(sdp, load_rows(fixture))
    assert manifest_path == str(sdp / MANIFEST_REL)

    written = (sdp / CSV_REL).read_bytes()
    expected = (DATA / fixture / CSV_REL).read_bytes()
    assert (
        hashlib.sha256(written).hexdigest()
        == CHECKSUMS["canonical_csv"][fixture]
    )
    assert written == expected

    # Manifest parity is contract-level: identical artifact binding (path,
    # sha256, row_count), honest per-implementation provenance.
    ours = json.loads((sdp / MANIFEST_REL).read_text(encoding="utf-8"))
    theirs = json.loads(
        (DATA / fixture / MANIFEST_REL).read_text(encoding="utf-8")
    )
    assert ours["schema_version"] == theirs["schema_version"] == "1.0"
    assert ours["artifact"] == theirs["artifact"]
    assert (
        ours["provenance"]["generated_by"]
        == "metasalmonpy.write_sdp_measurement_decompositions"
    )
    assert (
        theirs["provenance"]["generated_by"]
        == "metasalmon::write_sdp_measurement_decompositions"
    )
    assert ours["provenance"]["semantic_profile"] == (
        theirs["provenance"]["semantic_profile"]
    )


@pytest.mark.parametrize("fixture", FIXTURES)
def test_canonical_bytes_are_idempotent(fixture):
    rows = read_sdp_measurement_decompositions(DATA / fixture)
    assert decompositions._csv_bytes(rows) == (
        DATA / fixture / CSV_REL
    ).read_bytes()


@pytest.mark.parametrize("fixture", FIXTURES)
def test_python_validates_r_written_sdp(fixture):
    # Includes accepting R's writer provenance (PARITY.md entry 12).
    assert validate_sdp_measurement_decompositions(DATA / fixture) is True


def test_writer_is_deterministic_across_input_order(tmp_path):
    rows = load_rows("full-sdp")
    first = make_sdp(tmp_path, "full-sdp", "first")
    second = make_sdp(tmp_path, "full-sdp", "second")
    write_sdp_measurement_decompositions(first, rows)
    write_sdp_measurement_decompositions(
        second, rows.iloc[::-1].reset_index(drop=True)
    )
    assert (first / CSV_REL).read_bytes() == (second / CSV_REL).read_bytes()
    assert (first / MANIFEST_REL).read_bytes() == (
        second / MANIFEST_REL
    ).read_bytes()


def test_reader_returns_canonical_rows_and_manifest():
    result = read_sdp_measurement_decompositions(DATA / "era-sdp")
    assert list(result.columns) == list(decompositions._COLUMNS)
    assert result["component_order"].tolist() == [1, 2, 3, 4, 5, 6]
    assert result["component_label"].tolist()[3] == "Female sex constraint"
    # sdp-0.3.0's aggregation identity slot reads back exactly as R wrote it.
    assert result["component_role"].tolist()[4] == "statistical_modifier"
    assert result["component_status"].tolist()[4] == "gap"

    manifest = result.attrs["manifest"]
    assert manifest["schema_version"] == "1.0"
    assert manifest["artifact"]["path"] == (
        "metadata/semantic/measurement-decompositions.csv"
    )
    assert manifest["artifact"]["row_count"] == 6
    assert manifest["provenance"]["generated_by"] == (
        "metasalmon::write_sdp_measurement_decompositions"
    )


def test_canonical_sort_uses_c_collation_and_binding_keys():
    result = read_sdp_measurement_decompositions(DATA / "full-sdp")
    bindings = list(
        dict.fromkeys(
            zip(result["dataset_id"], result["table_id"], result["column_name"])
        )
    )
    # C collation: "Alpha..." < "demo...", and "Zsite" < "counts".
    assert bindings == [
        ("Alpha-DS-2027", "t1", "c1"),
        ("demo-salmon-2026", "Zsite", "flow"),
        ("demo-salmon-2026", "counts", "count"),
    ]
    counts = result[result["table_id"] == "counts"]
    assert counts["component_order"].tolist() == [1, 2, 3, 4, 5, 6, 7]


def test_quoted_unicode_fields_round_trip():
    result = read_sdp_measurement_decompositions(DATA / "full-sdp")
    labels = result["component_label"].tolist()
    assert 'Female, post-spawn — "sex" constraint; é' in labels
    rationales = result["rationale"].tolist()
    assert "No governed term; see review notes, item 4." in rationales


def test_relation_and_related_order_round_trip():
    result = read_sdp_measurement_decompositions(DATA / "full-sdp")
    relations = result["component_relation"].tolist()
    related = result["related_component_order"].tolist()
    linked = [row for row, value in enumerate(relations) if value]
    assert len(linked) == 1
    assert relations[linked[0]] == "value_of_dimension"
    assert related[linked[0]] == 3
    assert all(pd.isna(value) for row, value in enumerate(related) if row != linked[0])


# --- era component-state contract ----------------------------------------------


def test_statistical_modifier_role_is_accepted_and_method_is_not(tmp_path):
    # sdp-0.3.0 dropped the transitional method role: a decomposition row
    # binds one variable's identity, and a row-varying procedure would pin an
    # arbitrary one. The aggregation identity slot is statistical_modifier.
    rows = era_rows()
    assert "statistical_modifier" in rows["component_role"].tolist()
    assert "method" not in rows["component_role"].tolist()

    legacy = era_rows()
    legacy.loc[4, "component_role"] = "method"
    sdp = make_sdp(tmp_path, "era-sdp")
    with pytest.raises(ValueError, match="component_role must be one of"):
        write_sdp_measurement_decompositions(sdp, legacy)


@pytest.mark.parametrize(
    ("mutate", "message"),
    [
        (lambda rows: rows.__setitem__("component_status", rows["component_status"].replace({"matched": "review"})), "matched.*gap"),
        (lambda rows: rows.loc.__setitem__((0, "component_role"), "variable"), "component_role must be one of"),
        (lambda rows: rows.loc.__setitem__((0, "component_iri"), "qudt:Count"), "matched.*absolute.*IRI"),
        (lambda rows: rows.loc.__setitem__((3, "component_iri"), "https://example.org/Female"), "gap.*blank.*component_iri"),
        (lambda rows: rows.loc.__setitem__((3, "component_label"), ""), "gap.*component_label"),
        (lambda rows: rows.loc.__setitem__((3, "rationale"), ""), "gap.*rationale"),
        (lambda rows: rows.loc.__setitem__((0, "source"), ""), "source must be non-empty"),
        (lambda rows: rows.loc.__setitem__((0, "source_version"), ""), "source_version must be non-empty"),
        (lambda rows: rows.loc.__setitem__((0, "source_url"), "qudt.example/vocab"), "source_url.*absolute IRI"),
        (lambda rows: rows.loc.__setitem__((0, "provenance"), ""), "provenance must be non-empty"),
    ],
)
def test_matched_and_gap_rows_obey_the_closed_state_contract(
    tmp_path, mutate, message
):
    rows = era_rows()
    mutate(rows)
    sdp = make_sdp(tmp_path, "era-sdp")
    with pytest.raises(ValueError, match=message):
        write_sdp_measurement_decompositions(sdp, rows)


def test_component_order_is_contiguous_and_components_unique(tmp_path):
    duplicate_order = era_rows()
    duplicate_order.loc[5, "component_order"] = "5"
    with pytest.raises(ValueError, match="component_order must be unique"):
        write_sdp_measurement_decompositions(
            make_sdp(tmp_path, "era-sdp", "dup"), duplicate_order
        )

    skipped_order = era_rows()
    skipped_order.loc[5, "component_order"] = "7"
    with pytest.raises(ValueError, match="contiguous from 1"):
        write_sdp_measurement_decompositions(
            make_sdp(tmp_path, "era-sdp", "skip"), skipped_order
        )

    repeated = era_rows()
    extra = repeated.iloc[[0]].copy()
    extra["component_order"] = "7"
    repeated = pd.concat([repeated, extra], ignore_index=True)
    with pytest.raises(ValueError, match="Duplicate semantic component"):
        write_sdp_measurement_decompositions(
            make_sdp(tmp_path, "era-sdp", "repeat"), repeated
        )


def test_order_columns_accept_r_style_whole_numbers(tmp_path):
    # A pandas float64 order column (the dtype None forces) must behave
    # like R's numeric: whole values pass, fractions fail.
    rows = era_rows()
    rows["component_order"] = rows["component_order"].astype(float)
    rows["related_component_order"] = [None] * len(rows)
    sdp = make_sdp(tmp_path, "era-sdp")
    manifest_path = write_sdp_measurement_decompositions(sdp, rows)
    assert (sdp / CSV_REL).read_bytes() == (
        DATA / "era-sdp" / CSV_REL
    ).read_bytes()
    assert Path(manifest_path).exists()

    fractional = era_rows()
    fractional.loc[0, "component_order"] = "1.5"
    with pytest.raises(ValueError, match="positive whole numbers"):
        write_sdp_measurement_decompositions(
            make_sdp(tmp_path, "era-sdp", "frac"), fractional
        )


def test_rejects_schema_drift_in_the_input_frame(tmp_path):
    sdp = make_sdp(tmp_path, "era-sdp")
    missing = era_rows().drop(columns=["rationale"])
    with pytest.raises(ValueError, match="Missing columns: rationale"):
        write_sdp_measurement_decompositions(sdp, missing)

    unknown = era_rows()
    unknown["component_id"] = "smn:SpawnerStageContext"
    with pytest.raises(ValueError, match="Unknown columns: component_id"):
        write_sdp_measurement_decompositions(sdp, unknown)

    empty = era_rows().iloc[0:0]
    with pytest.raises(ValueError, match="non-empty data frame"):
        write_sdp_measurement_decompositions(sdp, empty)

    with pytest.raises(ValueError, match="non-empty data frame"):
        write_sdp_measurement_decompositions(sdp, "not-a-frame")

    nested = era_rows()
    nested_values = nested["component_label"].tolist()
    nested_values[0] = ["a", "list"]
    nested["component_label"] = pd.Series(nested_values, dtype=object)
    with pytest.raises(ValueError, match="scalar values"):
        write_sdp_measurement_decompositions(sdp, nested)


# --- relations -------------------------------------------------------------------


def find_relation_index(rows):
    return rows.index[rows["component_relation"] == "value_of_dimension"][0]


@pytest.mark.parametrize(
    ("mutate", "message"),
    [
        (
            lambda rows, i: rows.loc.__setitem__((i, "related_component_order"), ""),
            "both be populated or both be blank",
        ),
        (
            lambda rows, i: rows.loc.__setitem__((i, "component_relation"), ""),
            "both be populated or both be blank",
        ),
        (
            lambda rows, i: rows.loc.__setitem__((i, "component_relation"), "part_of"),
            "value_of_dimension",
        ),
        (
            lambda rows, i: rows.loc.__setitem__((i, "related_component_order"), "4"),
            "earlier component in the same measurement",
        ),
        (
            lambda rows, i: rows.loc.__setitem__((i, "related_component_order"), "2"),
            "matched constraint",
        ),
    ],
)
def test_dimension_relations_target_an_earlier_matched_constraint(
    tmp_path, mutate, message
):
    rows = relation_rows()
    mutate(rows, find_relation_index(rows))
    sdp = make_sdp(tmp_path, "full-sdp")
    with pytest.raises(ValueError, match=message):
        write_sdp_measurement_decompositions(sdp, rows)


# --- dictionary closure ------------------------------------------------------------


def test_decompositions_are_closed_over_the_exact_dictionary_binding(tmp_path):
    missing = era_rows()
    missing["column_name"] = "not_a_column"
    with pytest.raises(ValueError, match="does not exist in the SDP dictionary"):
        write_sdp_measurement_decompositions(
            make_sdp(tmp_path, "era-sdp", "missing"), missing
        )

    wrong_concept = era_rows()
    wrong_concept["measurement_concept_iri"] = (
        "https://w3id.org/psc/vocab/PSC-CV-000036"
    )
    with pytest.raises(ValueError, match="measurement_concept_iri.*term_iri"):
        write_sdp_measurement_decompositions(
            make_sdp(tmp_path, "era-sdp", "concept"), wrong_concept
        )

    # full-sdp's dictionary pins property_iri for the count measurement;
    # rewriting the matched property component breaks slot closure.
    wrong_property = relation_rows()
    property_index = wrong_property.index[
        (wrong_property["table_id"] == "counts")
        & (wrong_property["component_role"] == "property")
    ][0]
    wrong_property.loc[property_index, "component_iri"] = (
        "https://example.org/quantity-kind/EstimatedCount"
    )
    with pytest.raises(
        ValueError, match="property_iri value must appear as a matched property"
    ):
        write_sdp_measurement_decompositions(
            make_sdp(tmp_path, "full-sdp", "property"), wrong_property
        )


def test_dictionary_statistical_modifier_iri_requires_a_matched_component(tmp_path):
    # full-sdp's flow measurement pins statistical_modifier_iri in the
    # dictionary; the matched statistical_modifier component satisfying it
    # cannot be dropped or gapped.
    rows = relation_rows()
    modifier_index = rows.index[
        (rows["table_id"] == "Zsite")
        & (rows["component_role"] == "statistical_modifier")
    ][0]
    rows.loc[modifier_index, "component_iri"] = (
        "https://example.org/other-modifier"
    )
    sdp = make_sdp(tmp_path, "full-sdp")
    with pytest.raises(
        ValueError,
        match=(
            "statistical_modifier_iri value must appear as a matched "
            "statistical_modifier"
        ),
    ):
        write_sdp_measurement_decompositions(sdp, rows)


def test_semicolon_dictionary_constraints_are_checked_separately(tmp_path):
    # full-sdp's count measurement declares two semicolon-separated
    # constraint IRIs; dropping one matched constraint row breaks closure.
    rows = relation_rows()
    keep = ~(
        (rows["component_iri"] == "https://w3id.org/gcdfo/salmon#Age1YearClass")
        & (rows["component_role"] == "constraint")
    )
    rows = rows[keep].reset_index(drop=True)
    # Repair contiguity for the count measurement (orders 1..7 -> 1..6).
    counts = rows["table_id"] == "counts"
    orders = rows.loc[counts, "component_order"].astype(int)
    rows.loc[counts, "component_order"] = orders.rank().astype(int).astype(str)
    sdp = make_sdp(tmp_path, "full-sdp")
    with pytest.raises(
        ValueError,
        match="constraint_iri value must appear as a matched constraint "
        "component: https://w3id.org/gcdfo/salmon#Age1YearClass",
    ):
        write_sdp_measurement_decompositions(sdp, rows)


def test_non_measurement_and_ambiguous_dictionary_rows_are_rejected(tmp_path):
    role_sdp = make_sdp(tmp_path, "era-sdp", "role")
    dictionary_path = role_sdp / "metadata" / "column_dictionary.csv"
    dictionary = pd.read_csv(dictionary_path, dtype=str, keep_default_na=False)
    measurement = dictionary["column_name"] == "count"
    dictionary.loc[measurement, "column_role"] = "attribute"
    dictionary.to_csv(dictionary_path, index=False)
    with pytest.raises(ValueError, match="column_role other than"):
        write_sdp_measurement_decompositions(role_sdp, era_rows())

    duplicate_sdp = make_sdp(tmp_path, "era-sdp", "duplicate")
    dictionary_path = duplicate_sdp / "metadata" / "column_dictionary.csv"
    dictionary = pd.read_csv(dictionary_path, dtype=str, keep_default_na=False)
    dictionary = pd.concat(
        [dictionary, dictionary[dictionary["column_name"] == "count"]],
        ignore_index=True,
    )
    dictionary.to_csv(dictionary_path, index=False)
    with pytest.raises(ValueError, match="ambiguous duplicate"):
        write_sdp_measurement_decompositions(duplicate_sdp, era_rows())


def test_missing_dictionary_is_reported(tmp_path):
    sdp = tmp_path / "sdp"
    sdp.mkdir()
    with pytest.raises(
        FileNotFoundError, match="metadata/column_dictionary.csv"
    ):
        write_sdp_measurement_decompositions(sdp, era_rows())


# --- byte and manifest contracts ----------------------------------------------------


@pytest.mark.parametrize(
    ("mutate", "message"),
    [
        (lambda data: b"\xef\xbb\xbf" + data, "BOM"),
        (lambda data: data.replace(b"\n", b"\r\n"), "carriage"),
        (lambda data: data.replace("é".encode("utf-8"), b"\xff\xfe"), "UTF-8"),
        (lambda data: data[:-1], "final LF"),
        (lambda data: data + b"\x00\n", "NUL"),
    ],
)
def test_csv_bytes_are_utf8_lf_without_bom(tmp_path, mutate, message):
    sdp = make_sdp(tmp_path, "full-sdp")
    write_sdp_measurement_decompositions(sdp, load_rows("full-sdp"))
    csv_path = sdp / CSV_REL
    csv_path.write_bytes(mutate(csv_path.read_bytes()))
    rehash(sdp)
    with pytest.raises(ValueError, match=message):
        validate_sdp_measurement_decompositions(sdp)


def test_hash_drift_is_detected(written_sdp):
    csv_path = written_sdp / CSV_REL
    csv_path.write_bytes(
        csv_path.read_bytes().replace(b"Female sex", b"Female SEX")
    )
    with pytest.raises(ValueError, match="SHA-256"):
        validate_sdp_measurement_decompositions(written_sdp)


@pytest.mark.parametrize(
    ("mutate", "message"),
    [
        (
            lambda manifest: manifest["artifact"].__setitem__(
                "path", "../measurement-decompositions.csv"
            ),
            "artifact binding",
        ),
        (
            lambda manifest: manifest["artifact"].__setitem__("row_count", "6"),
            "whole number",
        ),
        (
            lambda manifest: manifest["artifact"].__setitem__("row_count", 7),
            "row count",
        ),
        (
            lambda manifest: manifest.__setitem__("schema_version", "9.9"),
            "schema version",
        ),
        (
            lambda manifest: manifest["provenance"].__setitem__(
                "generated_by", "another-writer"
            ),
            "writer provenance",
        ),
        (
            lambda manifest: manifest["provenance"].__setitem__(
                "metasalmonpy_version", ""
            ),
            "writer provenance",
        ),
        (
            lambda manifest: manifest.pop("provenance"),
            "missing required fields",
        ),
    ],
)
def test_the_manifest_is_a_closed_exact_byte_contract(
    written_sdp, mutate, message
):
    tamper_manifest(written_sdp, mutate)
    with pytest.raises(ValueError, match=message):
        validate_sdp_measurement_decompositions(written_sdp)


def test_missing_artifacts_are_reported(tmp_path):
    sdp = make_sdp(tmp_path, "era-sdp")
    with pytest.raises(FileNotFoundError, match="decomposition manifest"):
        validate_sdp_measurement_decompositions(sdp)

    write_sdp_measurement_decompositions(sdp, era_rows())
    (sdp / CSV_REL).unlink()
    with pytest.raises(FileNotFoundError, match="measurement decompositions"):
        validate_sdp_measurement_decompositions(sdp)


# --- writer semantics ------------------------------------------------------------------


def test_none_decompositions_are_an_explicit_noop(tmp_path):
    sdp = make_sdp(tmp_path, "era-sdp")
    assert write_sdp_measurement_decompositions(sdp, None) is None
    assert not (sdp / "metadata" / "semantic").exists()


def test_write_requires_existing_directory(tmp_path):
    with pytest.raises(ValueError, match="existing Salmon Data Package"):
        write_sdp_measurement_decompositions(tmp_path / "missing", era_rows())


def test_overwrite_is_explicit(written_sdp):
    with pytest.raises(FileExistsError, match="already exists.*overwrite"):
        write_sdp_measurement_decompositions(written_sdp, era_rows())

    updated = era_rows()
    updated.loc[3, "component_label"] = "Female constraint requiring review"
    write_sdp_measurement_decompositions(written_sdp, updated, overwrite=True)
    result = read_sdp_measurement_decompositions(written_sdp)
    assert (
        result["component_label"].tolist()[3]
        == "Female constraint requiring review"
    )


def test_write_cannot_escape_through_a_semantic_symlink(tmp_path):
    sdp = make_sdp(tmp_path, "era-sdp")
    outside = tmp_path / "outside"
    outside.mkdir()
    (sdp / "metadata" / "semantic").symlink_to(outside)
    with pytest.raises(ValueError, match="symlink"):
        write_sdp_measurement_decompositions(sdp, era_rows())
    assert not (outside / "measurement-decompositions.csv").exists()


def test_read_refuses_symlinked_semantic_artifacts(tmp_path):
    source = make_sdp(tmp_path, "era-sdp", "source")
    write_sdp_measurement_decompositions(source, era_rows())

    linked = make_sdp(tmp_path, "era-sdp", "linked")
    (linked / "metadata" / "semantic").symlink_to(
        source / "metadata" / "semantic"
    )
    with pytest.raises(ValueError, match="symlink"):
        validate_sdp_measurement_decompositions(linked)


def test_validate_flag_must_be_boolean():
    with pytest.raises(ValueError, match="validate must be True or False"):
        read_sdp_measurement_decompositions(DATA / "era-sdp", validate="yes")
    # validate=False still enforces the closed row schema and byte rules.
    result = read_sdp_measurement_decompositions(DATA / "era-sdp", validate=False)
    assert len(result) == 6


# --- written artifacts are ordinary files -------------------------------------------------


def test_written_artifacts_use_the_umask_default_mode(tmp_path):
    # R's writeBin + file.rename leaves the umask default (0644 typically);
    # tempfile.mkstemp hard-codes 0600 and os.replace preserves it, so the
    # decomposition CSV and manifest shipped private to their owner.
    sdp = make_sdp(tmp_path, "era-sdp")
    manifest_path = write_sdp_measurement_decompositions(sdp, era_rows())
    semantic = Path(manifest_path).parent

    reference = semantic / "reference.txt"
    reference.write_text("x", encoding="utf-8")
    expected = reference.stat().st_mode & 0o777

    for name in (
        "measurement-decompositions.csv",
        "measurement-decompositions.json",
    ):
        assert (semantic / name).stat().st_mode & 0o777 == expected, name


# --- public API --------------------------------------------------------------------------


def test_decomposition_entry_points_are_public():
    expected = {
        "read_sdp_measurement_decompositions",
        "write_sdp_measurement_decompositions",
        "validate_sdp_measurement_decompositions",
    }
    assert expected <= set(metasalmonpy.__all__)
    assert all(callable(getattr(metasalmonpy, name)) for name in expected)
